{
  "hash": "fc4cf1196716d5764eeae589064ad23a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home-Exercise 3\"\nauthor: \"Li Yuquan\"\ndescription: \"\"\ndate: \"October 26, 2025\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    code-fold: show\neditor: visual\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# 1 Overview\n\n## 1.1 Background\n\nHousing plays a crucial role in shaping household wealth and social stability, serving as both a financial asset and a fundamental human necessity. In Singapore, where land scarcity and housing affordability are persistent public concerns, understanding the determinants of resale housing prices is particularly important for policy formulation and urban planning.\n\nThe price of a housing unit is influenced by a combination of structural and locational factors. Structural factors include intrinsic attributes such as floor area, flat type, lease remaining, and renovation quality, while locational factors capture the spatial context—such as accessibility to public transport, schools, and amenities.\n\nTraditional modelling techniques, such as Ordinary Least Squares (OLS) regression, often fail to account for spatial autocorrelation and spatial heterogeneity inherent in housing data, leading to biased or inefficient estimates. To overcome these limitations, Geographically Weighted Models (GWMs) and other spatial econometric methods have been introduced to better capture local variations and spatial dependencies in housing markets.\n\n## 1.2 The Task\n\nThis take-home exercise aims to build a spatially informed predictive model to estimate and predict HDB resale prices in Singapore. Using transaction data from July 2024 to June 2025, the task involves calibrating a predictive model capable of forecasting resale prices for the period July to September 2025.\n\nThe model should integrate appropriate geospatial analytical techniques to account for spatial patterns in housing prices, identifying both structural and locational determinants that influence resale value. Through this spatially enhanced approach, the analysis seeks to provide more accurate price predictions and deeper insights into the spatial dynamics of Singapore’s housing market.\n\n## 1.3 Data Resources\n\n| Dataset Name | File / Object Name | Source |\n|------------------------|------------------------|------------------------|\n| Master Plan 2019 Subzone Boundary | `mpsz_cl.rds` | [data.gov.sg – Master Plan 2019 Subzone Boundary (No Sea)](https://data.gov.sg/datasets?query=Master+Plan+subzone+boundary&page=1&resultId=d_8594ae9ff96d0c708bc2af633048edfb) |\n| HDB Resale Transactions | `HDBresale.csv` | [data.gov.sg – HDB Resale Flat Prices](https://data.gov.sg/datasets?query=hdb+resale&page=1&resultId=d_8b84c4ee58e3cfc0ece0d773c8ca6abc) |\n| Preschools | `PreSchoolsLocation.kml` | [data.gov.sg – Preschool Locations](https://data.gov.sg/datasets?query=preschool) |\n| Eldercare Services | `EldercareServices.geojson` | [data.gov.sg – Eldercare Services](https://data.gov.sg/datasets?query=eldercare&page=1&resultId=d_3545b068e3f3506c56b2cb6b6117b884) |\n| Hawker Centres | `HawkerCentresGEOJSON.geojson` | [data.gov.sg – Hawker Centres](https://data.gov.sg/datasets?query=hawker+centre&page=1&resultId=d_4a086da0a5553be1d89383cd90d07ecd) |\n| Parks | `Parks.geojson` | [data.gov.sg – Parks](https://data.gov.sg/datasets?query=parks&page=1&resultId=d_0542d48f0991541706b58059381a6eca) |\n| Supermarkets | `SupermarketsGEOJSON.geojson` | [data.gov.sg – Supermarkets](https://data.gov.sg/datasets?query=supermarket&page=1&resultId=d_cac2c32f01960a3ad7202a99c27268a0) |\n| MRT / LRT Stations | `RapidTransitSystemStation.shp` | [LTA DataMall – Rapid Transit System Station](https://datamall.lta.gov.sg/content/datamall/en/static-data.html) |\n| Bus Stops | `BusStop.shp` | [LTA DataMall – Bus Stop Locations](https://datamall.lta.gov.sg/content/datamall/en/static-data.html) |\n| Kindergartens | `Kindergartens.geojson` | [data.gov.sg – Kindergartens](https://data.gov.sg/datasets?query=kindergarten) |\n| Childcare Services | `ChildCareServices.geojson` | [data.gov.sg – Child Care Services](https://data.gov.sg/datasets?query=childcare+services&page=1&resultId=d_5d668e3f544335f8028f546827b773b4) |\n| CHAS Clinics | `CHASClinics.geojson` | [data.gov.sg – CHAS Clinics](https://data.gov.sg/datasets?query=chas+clinics&page=1&resultId=d_548c33ea2d99e29ec63a7cc9edcccedc) |\n| General Information of Schools | `Generalinformationofschools.csv` | [data.gov.sg – General Information of Schools](https://data.gov.sg/datasets?query=school+information) |\n| Primary Schools (subset) | Filtered from `schools` | [data.gov.sg – General Information of Schools](https://data.gov.sg/datasets?query=school+information) |\n| Good Primary Schools | Filtered from `primary_schools` by name | Based on [schlah.com – Top Primary Schools](https://schlah.com/primary-schools) |\n| Central Business District (CBD) | Extracted “Downtown Core” centroid from `mpsz` | Derived from Master Plan 2019 Subzone Boundary |\n| Shopping Malls | `mall_coordinates_updated.csv` | [GitHub – Mall Coordinates Web Scraper](https://github.com/ValaryLim/Mall-Coordinates-Web-Scraper/blob/master/mall_coordinates_updated.csv) |\n\n## 1.4 R packages\n\n::: panel-tabset\n# Packages\n\n| Package | Purpose |\n|------------------------------------|------------------------------------|\n| **sf** | Manage and manipulate spatial vector data (simple features). |\n| **sp** | Support legacy spatial objects needed for certain spatial tests. |\n| **spdep** | Compute spatial weights and Moran’s I for spatial autocorrelation. |\n| **olsrr** | Perform OLS diagnostics, model summaries, and VIF checks. |\n| **ggplot2** | Create static plots for data visualization. |\n| **plotly** | Build interactive visualizations for exploratory analysis. |\n| **SpatialML** | Calibrate the Geographically Weighted Random Forest (gwRF) model. |\n| **tmap** | Produce thematic maps for spatial data visualization. |\n| **Metrics** | Evaluate model performance using RMSE and related metrics. |\n| **tidyverse** | Data wrangling and transformation using the tidy data framework. |\n| **httr** | Send HTTP requests to the OneMap Singapore API. |\n| **jsonlite** | Parse and process JSON responses from web APIs. |\n| **ggpubr** | Arrange multiple plots and create publication-ready figures. |\n| **stringr** | Clean and extract text data efficiently. |\n| **patchwork** | Combine multiple ggplot figures into composite layouts. |\n| **ggstatsplot** | Visualize correlation matrices and statistical relationships. |\n| **GWmodel** | Select adaptive bandwidth and perform geographically weighted analyses. |\n\n# The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, sp, spdep, olsrr, \n               ggplot2,plotly,\n               SpatialML, tmap,  \n               Metrics, \n               tidyverse, httr, \n               jsonlite,  \n               ggpubr, stringr,randomForest,\n               patchwork,\n               ggstatsplot,\n               GWmodel)\n```\n:::\n\n:::\n\n# 2 Data import and data prepare\n\n## 2.1 Data import\n\nA total of 16 datasets were imported in this section, including both aspatial and spatial data. The imported datasets cover HDB resale transactions, urban planning boundaries, and various locational amenities such as schools, childcare centres, healthcare facilities, and public infrastructure.\n\nSpecifically, the aspatial dataset (HDBresale.csv) already filter 4-room flats between July 2024 and September 2025.\n\nAll other datasets were read and transformed into the Singapore SVY21 coordinate reference system (EPSG:3414) to ensure consistency for subsequent spatial analysis and distance computation.\n\nIn total: **1 aspatial dataset** (HDB resale). **15 spatial datasets**, including subzone boundaries, amenities (preschools, eldercare, hawker centres, parks, supermarkets, MRT and bus stations), educational institutions (kindergartens, childcare centres, clinics, primary schools, good schools), urban centres (CBD), and shopping malls.\n\n::: panel-tabset\n# HDBresale\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_i <- read_csv(\n  \"data/rawdata/HDBresale.csv\"\n) %>%\n  filter(flat_type == \"4 ROOM\") %>%\n  filter(month >= \"2024-07\" & month <= \"2025-09\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14,737\nColumns: 11\n$ month               <chr> \"2024-07\", \"2024-07\", \"2024-07\", \"2024-07\", \"2024-…\n$ town                <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO …\n$ flat_type           <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", …\n$ block               <chr> \"335\", \"333\", \"226\", \"336\", \"303\", \"226\", \"337\", \"…\n$ street_name         <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 1\", \"ANG MO KI…\n$ storey_range        <chr> \"01 TO 03\", \"01 TO 03\", \"07 TO 09\", \"01 TO 03\", \"1…\n$ floor_area_sqm      <dbl> 91, 93, 91, 91, 97, 92, 91, 97, 94, 88, 102, 91, 8…\n$ flat_model          <chr> \"New Generation\", \"New Generation\", \"New Generatio…\n$ lease_commence_date <dbl> 1982, 1981, 1978, 1982, 1977, 1978, 1982, 1977, 20…\n$ remaining_lease     <chr> \"56 years 08 months\", \"55 years 08 months\", \"52 ye…\n$ resale_price        <dbl> 528888, 500000, 540000, 500000, 620000, 570000, 50…\n```\n\n\n:::\n:::\n\n\n# MPSZ\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = read_rds(\"data/rds/mpsz_cl.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 327\nColumns: 5\n$ REGION_N   <chr> \"CENTRAL REGION\", \"CENTRAL REGION\", \"CENTRAL REGION\", \"CENT…\n$ PLN_AREA_N <chr> \"BUKIT MERAH\", \"BUKIT MERAH\", \"OUTRAM\", \"DOWNTOWN CORE\", \"D…\n$ SUBZONE_N  <chr> \"DEPOT ROAD\", \"BUKIT MERAH\", \"CHINATOWN\", \"PHILLIP\", \"RAFFL…\n$ SUBZONE_C  <chr> \"BMSZ12\", \"BMSZ02\", \"OTSZ03\", \"DTSZ04\", \"DTSZ05\", \"OTSZ04\",…\n$ geometry   <MULTIPOLYGON [m]> MULTIPOLYGON (((25910.34 29..., MULTIPOLYGON (…\n```\n\n\n:::\n:::\n\n\n# preschool\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool <- st_read(\"data/rawdata/PreSchoolsLocation.kml\") %>% \n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/PreSchoolsLocation.kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(preschool)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,290\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <POINT [m]> POINT Z (25089.46 31299.16 0), POINT Z (27189.07 327…\n```\n\n\n:::\n:::\n\n\n# eldercare\n\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare <- st_read(\"data/rawdata/EldercareServices.geojson\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `EldercareServices' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/EldercareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 133 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.7119 ymin: 1.271472 xmax: 103.9561 ymax: 1.439561\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(eldercare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 133\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <POINT [m]> POINT Z (16614.08 36639.12 0), POINT Z (38803.81 350…\n```\n\n\n:::\n:::\n\n\n# hawker\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhawker <- st_read(\"data/rawdata/HawkerCentresGEOJSON.geojson\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SSOT_HAWKERCENTRES' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/HawkerCentresGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 129 features and 20 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6972 ymin: 1.272761 xmax: 103.9882 ymax: 1.448263\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(hawker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 129\nColumns: 21\n$ OBJECTID                     <int> 119091, 119092, 119093, 119094, 119095, 1…\n$ LANDXADDRESSPOINT            <dbl> 29433.15, 24814.32, 36371.37, 25229.98, 2…\n$ LANDYADDRESSPOINT            <dbl> 29089.98, 31095.01, 44035.87, 28415.04, 3…\n$ ADDRESSBUILDINGNAME          <chr> \"MND COMPLEX (ANNEXE B)\", \"SKYRESIDENCE @…\n$ ADDRESSPOSTALCODE            <chr> \"069111\", \"142038\", \"829911\", \"103078\", \"…\n$ ADDRESSSTREETNAME            <chr> \"MAXWELL ROAD\", \"Margaret Drive\", \"Punggo…\n$ DESCRIPTION                  <chr> \"HUP Standard Upgrading\", \"New Replacemen…\n$ NAME                         <chr> \"Amoy Street Food Centre (Telok Ayer Food…\n$ PHOTOURL                     <chr> \"http://www.nea.gov.sg/images/default-sou…\n$ ADDRESSBLOCKHOUSENUMBER      <chr> \"7\", \"38A\", \"84\", \"78C\", \"51\", \"2A\", \"27\"…\n$ STATUS                       <chr> \"Existing\", \"Existing (replacement)\", \"Ex…\n$ AWARDED_DATE                 <chr> NA, \"11/05/2015\", \"08/08/2019\", \"29/04/20…\n$ IMPLEMENTATION_DATE          <chr> NA, \"02/12/2015\", \"21/08/2019\", \"20/05/20…\n$ INFO_ON_CO_LOCATORS          <chr> NA, \"hawker centre/branch office\", \"hawke…\n$ ADDRESS_MYENV                <chr> \"National Development Building, Annex B, …\n$ EST_ORIGINAL_COMPLETION_DATE <chr> \"1983\", \"30/3/2022\", \"21/8/2024\", \"2027\",…\n$ HUP_COMPLETION_DATE          <chr> \"17/02/2003\", NA, NA, NA, NA, NA, NA, NA,…\n$ NUMBER_OF_COOKED_FOOD_STALLS <int> 134, 38, 40, 40, 82, 78, 40, 0, 80, 45, 5…\n$ INC_CRC                      <chr> \"1166A0D172748172\", \"939D0746E9A0AAE2\", \"…\n$ FMEL_UPD_D                   <chr> \"20250807100106\", \"20250807100106\", \"2025…\n$ geometry                     <POINT [m]> POINT (29480.26 29076.41), POINT (2…\n```\n\n\n:::\n:::\n\n\n# parks\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparks <- st_read(\"data/rawdata/Parks.geojson\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Parks' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/Parks.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 441 features and 4 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6929 ymin: 1.264367 xmax: 104.0538 ymax: 1.461944\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(parks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 441\nColumns: 5\n$ OBJECTID <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ NAME     <chr> \"LABRADOR NATURE RESERVE\", \"BUKIT TIMAH NATURE RESERVE\", \"UPP…\n$ X        <dbl> 24518.62, 21965.93, 25120.07, 25612.60, 26744.71, 26657.96, 2…\n$ Y        <dbl> 27763.35, 37350.60, 42569.94, 39421.77, 40510.92, 37655.25, 3…\n$ geometry <POINT [m]> POINT (24518.62 27763.35), POINT (21965.93 37350.6), PO…\n```\n\n\n:::\n:::\n\n\n# supermarkets\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupermarkets <- st_read(\"data/rawdata/SupermarketsGEOJSON.geojson\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SupermarketsGEOJSON' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/SupermarketsGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 526 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6258 ymin: 1.24715 xmax: 104.0036 ymax: 1.461526\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(supermarkets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 526\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <POINT [m]> POINT Z (35561.22 42685.17 0), POINT Z (32184.01 329…\n```\n\n\n:::\n:::\n\n\n# MRT station\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt_station <- st_read(\"data/rawdata/RapidTransitSystemStation/RapidTransitSystemStation.shp\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `RapidTransitSystemStation' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/RapidTransitSystemStation/RapidTransitSystemStation.shp' \n  using driver `ESRI Shapefile'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 231 features and 7 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 6068.209 ymin: 27478.44 xmax: 45377.5 ymax: 47913.58\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mrt_station)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 231\nColumns: 8\n$ TYP_CD     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ STN_NAM    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ ATTACHEMEN <chr> NA, NA, NA, \"NE14_HGN STN.zip\", NA, NA, \"C504_S_CGA_MAIN_A_…\n$ SHAPE_AREA <dbl> 1054.6116, 6110.8140, 11496.4690, 10872.9669, 4710.6458, 40…\n$ SHAPE_LEN  <dbl> 170.5610, 560.7463, 795.6252, 782.5585, 384.7860, 375.6870,…\n$ TYP_CD_DES <chr> \"LRT\", \"MRT\", \"MRT\", \"MRT\", \"MRT\", \"MRT\", \"MRT\", \"LRT\", \"LR…\n$ STN_NAM_DE <chr> \"CORAL EDGE LRT STATION\", \"DHOBY GHAUT MRT STATION\", \"LAVEN…\n$ geometry   <MULTIPOLYGON [m]> MULTIPOLYGON (((36786.93 41..., MULTIPOLYGON (…\n```\n\n\n:::\n:::\n\n\n# bus stop\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_stop <- st_read(\"data/rawdata/BusStop/BusStop.shp\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/BusStop/BusStop.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5172 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(bus_stop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,172\nColumns: 3\n$ BUS_STOP_N <chr> \"65059\", \"16171\", \"61101\", \"01239\", \"17269\", \"11291\", \"1153…\n$ LOC_DESC   <chr> \"ST ANNE'S CH\", \"YUSOF ISHAK HSE\", \"BLK 120\", \"SULTAN PLAZA…\n$ geometry   <POINT [m]> POINT (35565.66 41659.52), POINT (21439.91 31253.63),…\n```\n\n\n:::\n:::\n\n\n# kindergartens\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkindergartens <- st_read(\"data/rawdata/Kindergartens.geojson\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Kindergartens' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/Kindergartens.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 448 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6887 ymin: 1.247759 xmax: 103.9717 ymax: 1.455452\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(kindergartens)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 448\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <POINT [m]> POINT Z (30325.45 38859.25 0), POINT Z (30190.51 395…\n```\n\n\n:::\n:::\n\n\n# childcare\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare <- st_read(\"data/rawdata/ChildCareServices.geojson\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ChildCareServices' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/ChildCareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1925 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(childcare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,925\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <POINT [m]> POINT Z (40985.94 33848.38 0), POINT Z (28308.65 455…\n```\n\n\n:::\n:::\n\n\n# clinics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclinics <- st_read(\"data/rawdata/CHASClinics.geojson\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHASClinics' from data source \n  `/Users/liyuquan/yuquan6688/626_yuquan/Take-home_Ex/Take-home_Ex03/data/rawdata/CHASClinics.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1193 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.5818 ymin: 1.016264 xmax: 103.9903 ymax: 1.456037\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(clinics)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,193\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <POINT [m]> POINT Z (10760.19 34206.12 0), POINT Z (4985.534 301…\n```\n\n\n:::\n:::\n\n\n# schools\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschools <- read_csv(\"data/rawdata/Generalinformationofschools.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 337\nColumns: 31\n$ school_name        <chr> \"ADMIRALTY PRIMARY SCHOOL\", \"ADMIRALTY SECONDARY SC…\n$ url_address        <chr> \"https://admiraltypri.moe.edu.sg/\", \"http://www.adm…\n$ address            <chr> \"11 WOODLANDS CIRCLE\", \"31 WOODLANDS CRESCENT\", \"10…\n$ postal_code        <dbl> 738907, 737916, 768643, 768928, 579646, 159016, 544…\n$ telephone_no       <chr> \"63620598\", \"63651733\", \"67592906\", \"67585384\", \"64…\n$ telephone_no_2     <chr> \"na\", \"63654596\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fax_no             <chr> \"63627512\", \"63652774\", \"67592927\", \"67557778\", \"64…\n$ fax_no_2           <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ email_address      <chr> \"ADMIRALTY_PS@MOE.EDU.SG\", \"Admiralty_SS@moe.edu.sg…\n$ mrt_desc           <chr> \"Admiralty Station\", \"ADMIRALTY MRT\", \"Yishun\", \"CA…\n$ bus_desc           <chr> \"TIBS 965, 964, 913\", \"904\", \"Yishun Ring Road - 81…\n$ principal_name     <chr> \"MR CHEN ZHONGYI\", \"MR TAN KELLY\", \"MS BAEY EE-LYN\"…\n$ first_vp_name      <chr> \"MADAM CHUA MUI LING\", \"MR CHAN YEW REN EUGENE\", \"M…\n$ second_vp_name     <chr> \"MR HAMRI BIN A JALIL\", \"MR TAN HOCK CHUAN MICHAEL\"…\n$ third_vp_name      <chr> \"na\", \"na\", \"na\", \"MISS LATIFAH BTE ABDUL LATIFF\", …\n$ fourth_vp_name     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fifth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ sixth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ dgp_code           <chr> \"WOODLANDS\", \"WOODLANDS\", \"YISHUN\", \"YISHUN\", \"BISH…\n$ zone_code          <chr> \"NORTH\", \"NORTH\", \"NORTH\", \"NORTH\", \"SOUTH\", \"SOUTH…\n$ type_code          <chr> \"GOVERNMENT SCHOOL\", \"GOVERNMENT SCHOOL\", \"GOVERNME…\n$ nature_code        <chr> \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO…\n$ session_code       <chr> \"FULL DAY\", \"SINGLE SESSION\", \"SINGLE SESSION\", \"SI…\n$ mainlevel_code     <chr> \"PRIMARY\", \"SECONDARY (S1-S5)\", \"PRIMARY\", \"SECONDA…\n$ sap_ind            <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"N…\n$ autonomous_ind     <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Ye…\n$ gifted_ind         <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ ip_ind             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ mothertongue1_code <chr> \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINES…\n$ mothertongue2_code <chr> \"MALAY\", \"MALAY\", \"MALAY\", \"MALAY\", \"na\", \"MALAY\", …\n$ mothertongue3_code <chr> \"TAMIL\", \"TAMIL\", \"TAMIL\", \"TAMIL\", \"na\", \"TAMIL\", …\n```\n\n\n:::\n:::\n\n\n# primary schools\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_schools <- schools %>%\n  filter(mainlevel_code == \"PRIMARY\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(primary_schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 179\nColumns: 31\n$ school_name        <chr> \"ADMIRALTY PRIMARY SCHOOL\", \"AHMAD IBRAHIM PRIMARY …\n$ url_address        <chr> \"https://admiraltypri.moe.edu.sg/\", \"http://www.ahm…\n$ address            <chr> \"11 WOODLANDS CIRCLE\", \"10 YISHUN STREET 11\", \"100 …\n$ postal_code        <dbl> 738907, 768643, 579646, 159016, 544969, 569785, 569…\n$ telephone_no       <chr> \"63620598\", \"67592906\", \"64547672\", \"62485400\", \"68…\n$ telephone_no_2     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"67337912…\n$ fax_no             <chr> \"63627512\", \"67592927\", \"64532726\", \"62485409\", \"63…\n$ fax_no_2           <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ email_address      <chr> \"ADMIRALTY_PS@MOE.EDU.SG\", \"AIPS@MOE.EDU.SG\", \"AITO…\n$ mrt_desc           <chr> \"Admiralty Station\", \"Yishun\", \"Bishan MRT\", \"Redhi…\n$ bus_desc           <chr> \"TIBS 965, 964, 913\", \"Yishun Ring Road - 812 (whit…\n$ principal_name     <chr> \"MR CHEN ZHONGYI\", \"MS BAEY EE-LYN\", \"MR WONG JIA W…\n$ first_vp_name      <chr> \"MADAM CHUA MUI LING\", \"MADAM YEO SIAU YEN\", \"MR YA…\n$ second_vp_name     <chr> \"MR HAMRI BIN A JALIL\", \"MADAM ZHANG JUNLI\", \"MR CH…\n$ third_vp_name      <chr> \"na\", \"na\", \"MR KHOO THIAM HUAT\", \"na\", \"na\", \"na\",…\n$ fourth_vp_name     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fifth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ sixth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ dgp_code           <chr> \"WOODLANDS\", \"YISHUN\", \"BISHAN\", \"BUKIT MERAH\", \"SE…\n$ zone_code          <chr> \"NORTH\", \"NORTH\", \"SOUTH\", \"SOUTH\", \"NORTH\", \"NORTH…\n$ type_code          <chr> \"GOVERNMENT SCHOOL\", \"GOVERNMENT SCHOOL\", \"GOVERNME…\n$ nature_code        <chr> \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO…\n$ session_code       <chr> \"FULL DAY\", \"SINGLE SESSION\", \"SINGLE SESSION\", \"SI…\n$ mainlevel_code     <chr> \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMAR…\n$ sap_ind            <chr> \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"N…\n$ autonomous_ind     <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ gifted_ind         <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Ye…\n$ ip_ind             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ mothertongue1_code <chr> \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINES…\n$ mothertongue2_code <chr> \"MALAY\", \"MALAY\", \"na\", \"MALAY\", \"MALAY\", \"MALAY\", …\n$ mothertongue3_code <chr> \"TAMIL\", \"TAMIL\", \"na\", \"TAMIL\", \"TAMIL\", \"TAMIL\", …\n```\n\n\n:::\n:::\n\n\n# good school\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngood_primary_school_list <- c(\n \"NANYANG PRIMARY SCHOOL\", \"TAO NAN SCHOOL\", \"Hong Wen School\", \"NAN HUA PRIMARY SCHOOL\", \"ST. HILDA'S PRIMARY SCHOOL\", \"HENRY PARK PRIMARY SCHOOL\", \"ANGLO-CHINESE SCHOOL (PRIMARY)\", \"RAFFLES GIRLS' PRIMARY SCHOOL\", \"PEI HWA PRESBYTERIAN PRIMARY SCHOOL\", \"Radin Mas Primary School\", \"ROSYTH SCHOOL\", \"KONG HWA SCHOOL\", \"POI CHING SCHOOL\", \"HOLY INNOCENTS' PRIMARY SCHOOL\", \"AI TONG SCHOOL\", \"RED SWASTIKA SCHOOL\", \"Maha Bodhi School\", \"RULANG PRIMARY SCHOOL\", \"PEI CHUN PUBLIC SCHOOL\", \"SINGAPORE CHINESE GIRLS' PRIMARY SCHOOL\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngood_primary_schools <- primary_schools %>%\n  filter(school_name %in% toupper(good_primary_school_list))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(good_primary_schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 20\nColumns: 31\n$ school_name        <chr> \"AI TONG SCHOOL\", \"ANGLO-CHINESE SCHOOL (PRIMARY)\",…\n$ url_address        <chr> \"http://www.aitong.moe.edu.sg\", \"http://www.acspri.…\n$ address            <chr> \"100 Bright Hill Drive\", \"50 BARKER ROAD\", \"1 HOLLA…\n$ postal_code        <dbl> 579646, 309918, 278790, 536451, 327829, 399772, 408…\n$ telephone_no       <chr> \"64547672\", \"62501633\", \"64663600\", \"62886516\", \"62…\n$ telephone_no_2     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fax_no             <chr> \"64532726\", \"63531366\", \"64691840\", \"62876393\", \"62…\n$ fax_no_2           <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ email_address      <chr> \"AITONG_SCH@MOE.EDU.SG\", \"ACPS@MOE.EDU.SG\", \"HPPS@M…\n$ mrt_desc           <chr> \"Bishan MRT\", \"Newton MRT Station\", \"Buona Vista MR…\n$ bus_desc           <chr> \"410, 162, 52\", \"Bus 48, 66, 67, 170, 960, 972M\", \"…\n$ principal_name     <chr> \"MR WONG JIA WANG\", \"MRS LEONG-HO HIL MAY\", \"MR CHA…\n$ first_vp_name      <chr> \"MR YAK BENG WEI\", \"MR CHUA THIAN KEONG\", \"MR CHUA …\n$ second_vp_name     <chr> \"MR CHIU SHEK MAN PHILIP\", \"MADAM TEH HSIAO CHUIN\",…\n$ third_vp_name      <chr> \"MR KHOO THIAM HUAT\", \"MADAM SEOW LAY YEN\", \"MISS R…\n$ fourth_vp_name     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fifth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ sixth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ dgp_code           <chr> \"BISHAN\", \"NOVENA\", \"BUKIT TIMAH\", \"HOUGANG\", \"KALL…\n$ zone_code          <chr> \"SOUTH\", \"SOUTH\", \"WEST\", \"SOUTH\", \"SOUTH\", \"EAST\",…\n$ type_code          <chr> \"GOVERNMENT-AIDED SCH\", \"GOVERNMENT-AIDED SCH\", \"GO…\n$ nature_code        <chr> \"CO-ED SCHOOL\", \"BOYS' SCHOOL\", \"CO-ED SCHOOL\", \"CO…\n$ session_code       <chr> \"SINGLE SESSION\", \"SINGLE SESSION\", \"SINGLE SESSION…\n$ mainlevel_code     <chr> \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMAR…\n$ sap_ind            <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes…\n$ autonomous_ind     <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ gifted_ind         <chr> \"No\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"Yes\", …\n$ ip_ind             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ mothertongue1_code <chr> \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINES…\n$ mothertongue2_code <chr> \"na\", \"MALAY\", \"MALAY\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ mothertongue3_code <chr> \"na\", \"TAMIL\", \"TAMIL\", \"na\", \"na\", \"na\", \"na\", \"na…\n```\n\n\n:::\n:::\n\n\n# CBD\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbd_poly <- mpsz %>%\n  filter(PLN_AREA_N == \"DOWNTOWN CORE\") %>%\n  st_union()\n\ncbd <- st_point_on_surface(cbd_poly)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(cbd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsfc_POINT of length 1; first list element:  'XY' num [1:2] 30534 29890\n```\n\n\n:::\n:::\n\n\n# Shopping Mall\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshopping <- read_csv(\"data/rawdata/mall_coordinates_updated.csv\") %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(shopping)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 184\nColumns: 3\n$ ...1     <dbl> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…\n$ name     <chr> \"100 AM\", \"112 KATONG\", \"313@SOMERSET\", \"321 CLEMENTI\", \"600 …\n$ geometry <POINT [m]> POINT (29129.86 28563.01), POINT (35988.49 31935.5), PO…\n```\n\n\n:::\n:::\n\n:::\n\n## 2.2 OneMap Geocoding Function\n\nThis section performs geocoding using the Singapore OneMap API, transforming postal codes and address information into geographic coordinates for spatial analysis.\n\nThe function get_coords() was developed to batch-geocode postal codes for the schools, primary schools, and good primary schools datasets. It queries the OneMap endpoint to retrieve latitude and longitude, filters out invalid results, and converts the output into spatial features using the WGS84 coordinate system, later reprojected to SVY21 (EPSG:3414) for spatial consistency.\n\nFor the HDB resale dataset, the function geocode() was created to obtain coordinates based on the concatenation of block and street name. The retrieved coordinates were appended to each record, converting the aspatial HDB dataset into a spatial object. After transformation to the SVY21 projection, all datasets were spatially aligned for subsequent spatial analysis and modelling.\n\n::: panel-tabset\n# Postal Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_coords <- function(search_list){\n  \n  coord_df <- data.frame()\n  \n  for (item in search_list){\n    r <- GET('https://www.onemap.gov.sg/api/common/elastic/search?',\n             query=list(searchVal=item,\n                        returnGeom='Y',\n                        getAddrDetails='Y'))\n    data <- fromJSON(rawToChar(r$content))\n    found <- data$found\n    res <- data$results\n    \n    new_row <- data.frame()\n    \n    if (found == 1){\n      new_row <- data.frame(\n        search_val = item,\n        postal = res$POSTAL,\n        latitude = res$LATITUDE,\n        longitude = res$LONGITUDE\n      )\n    }\n    \n    else if (found > 1){\n      res_sub <- res[res$POSTAL != \"NIL\", ]\n      \n      if (nrow(res_sub) == 0){\n        new_row <- data.frame(search_val = item,\n                              postal = NA,\n                              latitude = NA,\n                              longitude = NA)\n      } else {\n        top1 <- head(res_sub, 1)\n        new_row <- data.frame(\n          search_val = item,\n          postal = top1$POSTAL,\n          latitude = top1$LATITUDE,\n          longitude = top1$LONGITUDE\n        )\n      }\n    }\n    \n    else {\n      new_row <- data.frame(search_val = item,\n                            postal = NA,\n                            latitude = NA,\n                            longitude = NA)\n    }\n    \n    coord_df <- rbind(coord_df, new_row)\n  }\n  \n  return(coord_df)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_postal_list <- schools$postal_code %>%\n  as.character() %>%\n  sprintf(\"%06s\", .)\n\nschool_coords <- get_coords(school_postal_list)\n\nschools <- bind_cols(\n  schools,\n  school_coords %>%\n    transmute(\n      latitude  = as.numeric(latitude),\n      longitude = as.numeric(longitude)\n    )\n)\n\n\nschools <- schools %>%\n  filter(!is.na(longitude), !is.na(latitude)) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>% \n  st_transform(3414) \n\nglimpse(schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 337\nColumns: 32\n$ school_name        <chr> \"ADMIRALTY PRIMARY SCHOOL\", \"ADMIRALTY SECONDARY SC…\n$ url_address        <chr> \"https://admiraltypri.moe.edu.sg/\", \"http://www.adm…\n$ address            <chr> \"11 WOODLANDS CIRCLE\", \"31 WOODLANDS CRESCENT\", \"10…\n$ postal_code        <dbl> 738907, 737916, 768643, 768928, 579646, 159016, 544…\n$ telephone_no       <chr> \"63620598\", \"63651733\", \"67592906\", \"67585384\", \"64…\n$ telephone_no_2     <chr> \"na\", \"63654596\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fax_no             <chr> \"63627512\", \"63652774\", \"67592927\", \"67557778\", \"64…\n$ fax_no_2           <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ email_address      <chr> \"ADMIRALTY_PS@MOE.EDU.SG\", \"Admiralty_SS@moe.edu.sg…\n$ mrt_desc           <chr> \"Admiralty Station\", \"ADMIRALTY MRT\", \"Yishun\", \"CA…\n$ bus_desc           <chr> \"TIBS 965, 964, 913\", \"904\", \"Yishun Ring Road - 81…\n$ principal_name     <chr> \"MR CHEN ZHONGYI\", \"MR TAN KELLY\", \"MS BAEY EE-LYN\"…\n$ first_vp_name      <chr> \"MADAM CHUA MUI LING\", \"MR CHAN YEW REN EUGENE\", \"M…\n$ second_vp_name     <chr> \"MR HAMRI BIN A JALIL\", \"MR TAN HOCK CHUAN MICHAEL\"…\n$ third_vp_name      <chr> \"na\", \"na\", \"na\", \"MISS LATIFAH BTE ABDUL LATIFF\", …\n$ fourth_vp_name     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fifth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ sixth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ dgp_code           <chr> \"WOODLANDS\", \"WOODLANDS\", \"YISHUN\", \"YISHUN\", \"BISH…\n$ zone_code          <chr> \"NORTH\", \"NORTH\", \"NORTH\", \"NORTH\", \"SOUTH\", \"SOUTH…\n$ type_code          <chr> \"GOVERNMENT SCHOOL\", \"GOVERNMENT SCHOOL\", \"GOVERNME…\n$ nature_code        <chr> \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO…\n$ session_code       <chr> \"FULL DAY\", \"SINGLE SESSION\", \"SINGLE SESSION\", \"SI…\n$ mainlevel_code     <chr> \"PRIMARY\", \"SECONDARY (S1-S5)\", \"PRIMARY\", \"SECONDA…\n$ sap_ind            <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"N…\n$ autonomous_ind     <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Ye…\n$ gifted_ind         <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ ip_ind             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ mothertongue1_code <chr> \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINES…\n$ mothertongue2_code <chr> \"MALAY\", \"MALAY\", \"MALAY\", \"MALAY\", \"na\", \"MALAY\", …\n$ mothertongue3_code <chr> \"TAMIL\", \"TAMIL\", \"TAMIL\", \"TAMIL\", \"na\", \"TAMIL\", …\n$ geometry           <POINT [m]> POINT (24296.63 47144.77), POINT (24559.05 47…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_postal_list <- primary_schools$postal_code %>%\n  as.character() %>%\n  sprintf(\"%06s\", .)\n\nprimary_coords <- get_coords(primary_postal_list)\n\nprimary_schools <- bind_cols(\n  primary_schools,\n  primary_coords %>%\n    transmute(\n      latitude  = as.numeric(latitude),\n      longitude = as.numeric(longitude)\n    )\n)\n\nprimary_schools <- primary_schools %>%\n  filter(!is.na(longitude), !is.na(latitude)) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(3414)\n\nglimpse(primary_schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 179\nColumns: 32\n$ school_name        <chr> \"ADMIRALTY PRIMARY SCHOOL\", \"AHMAD IBRAHIM PRIMARY …\n$ url_address        <chr> \"https://admiraltypri.moe.edu.sg/\", \"http://www.ahm…\n$ address            <chr> \"11 WOODLANDS CIRCLE\", \"10 YISHUN STREET 11\", \"100 …\n$ postal_code        <dbl> 738907, 768643, 579646, 159016, 544969, 569785, 569…\n$ telephone_no       <chr> \"63620598\", \"67592906\", \"64547672\", \"62485400\", \"68…\n$ telephone_no_2     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"67337912…\n$ fax_no             <chr> \"63627512\", \"67592927\", \"64532726\", \"62485409\", \"63…\n$ fax_no_2           <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ email_address      <chr> \"ADMIRALTY_PS@MOE.EDU.SG\", \"AIPS@MOE.EDU.SG\", \"AITO…\n$ mrt_desc           <chr> \"Admiralty Station\", \"Yishun\", \"Bishan MRT\", \"Redhi…\n$ bus_desc           <chr> \"TIBS 965, 964, 913\", \"Yishun Ring Road - 812 (whit…\n$ principal_name     <chr> \"MR CHEN ZHONGYI\", \"MS BAEY EE-LYN\", \"MR WONG JIA W…\n$ first_vp_name      <chr> \"MADAM CHUA MUI LING\", \"MADAM YEO SIAU YEN\", \"MR YA…\n$ second_vp_name     <chr> \"MR HAMRI BIN A JALIL\", \"MADAM ZHANG JUNLI\", \"MR CH…\n$ third_vp_name      <chr> \"na\", \"na\", \"MR KHOO THIAM HUAT\", \"na\", \"na\", \"na\",…\n$ fourth_vp_name     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fifth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ sixth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ dgp_code           <chr> \"WOODLANDS\", \"YISHUN\", \"BISHAN\", \"BUKIT MERAH\", \"SE…\n$ zone_code          <chr> \"NORTH\", \"NORTH\", \"SOUTH\", \"SOUTH\", \"NORTH\", \"NORTH…\n$ type_code          <chr> \"GOVERNMENT SCHOOL\", \"GOVERNMENT SCHOOL\", \"GOVERNME…\n$ nature_code        <chr> \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO-ED SCHOOL\", \"CO…\n$ session_code       <chr> \"FULL DAY\", \"SINGLE SESSION\", \"SINGLE SESSION\", \"SI…\n$ mainlevel_code     <chr> \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMAR…\n$ sap_ind            <chr> \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"N…\n$ autonomous_ind     <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ gifted_ind         <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Ye…\n$ ip_ind             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ mothertongue1_code <chr> \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINES…\n$ mothertongue2_code <chr> \"MALAY\", \"MALAY\", \"na\", \"MALAY\", \"MALAY\", \"MALAY\", …\n$ mothertongue3_code <chr> \"TAMIL\", \"TAMIL\", \"na\", \"TAMIL\", \"TAMIL\", \"TAMIL\", …\n$ geometry           <POINT [m]> POINT (24296.63 47144.77), POINT (27958.14 46…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngood_postal_list <- good_primary_schools$postal_code %>%\n  as.character() %>%\n  sprintf(\"%06s\", .)\n\ngood_coords <- get_coords(good_postal_list)\n\ngood_primary_schools <- bind_cols(\n  good_primary_schools,\n  good_coords %>%\n    transmute(\n      latitude  = as.numeric(latitude),\n      longitude = as.numeric(longitude)\n    )\n)\n\ngood_primary_schools <- good_primary_schools %>%\n  filter(!is.na(longitude), !is.na(latitude)) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(3414)\n\nglimpse(good_primary_schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 20\nColumns: 32\n$ school_name        <chr> \"AI TONG SCHOOL\", \"ANGLO-CHINESE SCHOOL (PRIMARY)\",…\n$ url_address        <chr> \"http://www.aitong.moe.edu.sg\", \"http://www.acspri.…\n$ address            <chr> \"100 Bright Hill Drive\", \"50 BARKER ROAD\", \"1 HOLLA…\n$ postal_code        <dbl> 579646, 309918, 278790, 536451, 327829, 399772, 408…\n$ telephone_no       <chr> \"64547672\", \"62501633\", \"64663600\", \"62886516\", \"62…\n$ telephone_no_2     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fax_no             <chr> \"64532726\", \"63531366\", \"64691840\", \"62876393\", \"62…\n$ fax_no_2           <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ email_address      <chr> \"AITONG_SCH@MOE.EDU.SG\", \"ACPS@MOE.EDU.SG\", \"HPPS@M…\n$ mrt_desc           <chr> \"Bishan MRT\", \"Newton MRT Station\", \"Buona Vista MR…\n$ bus_desc           <chr> \"410, 162, 52\", \"Bus 48, 66, 67, 170, 960, 972M\", \"…\n$ principal_name     <chr> \"MR WONG JIA WANG\", \"MRS LEONG-HO HIL MAY\", \"MR CHA…\n$ first_vp_name      <chr> \"MR YAK BENG WEI\", \"MR CHUA THIAN KEONG\", \"MR CHUA …\n$ second_vp_name     <chr> \"MR CHIU SHEK MAN PHILIP\", \"MADAM TEH HSIAO CHUIN\",…\n$ third_vp_name      <chr> \"MR KHOO THIAM HUAT\", \"MADAM SEOW LAY YEN\", \"MISS R…\n$ fourth_vp_name     <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ fifth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ sixth_vp_name      <chr> \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ dgp_code           <chr> \"BISHAN\", \"NOVENA\", \"BUKIT TIMAH\", \"HOUGANG\", \"KALL…\n$ zone_code          <chr> \"SOUTH\", \"SOUTH\", \"WEST\", \"SOUTH\", \"SOUTH\", \"EAST\",…\n$ type_code          <chr> \"GOVERNMENT-AIDED SCH\", \"GOVERNMENT-AIDED SCH\", \"GO…\n$ nature_code        <chr> \"CO-ED SCHOOL\", \"BOYS' SCHOOL\", \"CO-ED SCHOOL\", \"CO…\n$ session_code       <chr> \"SINGLE SESSION\", \"SINGLE SESSION\", \"SINGLE SESSION…\n$ mainlevel_code     <chr> \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMARY\", \"PRIMAR…\n$ sap_ind            <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes…\n$ autonomous_ind     <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ gifted_ind         <chr> \"No\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"Yes\", …\n$ ip_ind             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No…\n$ mothertongue1_code <chr> \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINESE\", \"CHINES…\n$ mothertongue2_code <chr> \"na\", \"MALAY\", \"MALAY\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ mothertongue3_code <chr> \"na\", \"TAMIL\", \"TAMIL\", \"na\", \"na\", \"na\", \"na\", \"na…\n$ geometry           <POINT [m]> POINT (27966.81 38071.92), POINT (28254.98 33…\n```\n\n\n:::\n:::\n\n\n# Address\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_i$street_name <- gsub(\n  \"ST\\\\.\", \"SAINT\",\n  HDBresale_i$street_name)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\n    \"searchVal\" = address,\n    \"returnGeom\" = \"Y\",\n    \"getAddrDetails\" = \"N\",\n    \"pageNum\" = \"1\"\n  )\n  \n  res <- GET(base_url, query = query)\n  restext <- content(res, as = \"text\")\n  \n  output <- fromJSON(restext) %>%\n    as.data.frame() %>%\n    select(results.LATITUDE, results.LONGITUDE)\n  \n  return(output)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Executing Geocoding and Assigning Coordinates\nHDBresale_i$LATITUDE <- 0\nHDBresale_i$LONGITUDE <- 0\n\nfor (i in 1:nrow(HDBresale_i)) {\n  temp_output <- geocode(HDBresale_i[i, 4], HDBresale_i[i, 5])\n  \n  HDBresale_i$LATITUDE[i]  <- temp_output$results.LATITUDE\n  HDBresale_i$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#  Converting to Spatial Features (WGS84 → SVY21 / EPSG:3414)\nHDBresale_i <- HDBresale_i %>%\n  st_as_sf(\n    coords = c(\"LONGITUDE\", \"LATITUDE\"), \n    crs = 4326) %>%\n  st_transform(crs = 3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(HDBresale_i, \"data/rds/HDBresale_i.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n:::\n\n## 2.3 Geometry Simplification\n\nThis step removes unnecessary Z and M dimensions from the spatial datasets using st_zm(). Since all analyses only require two-dimensional (X–Y) geometries, this process ensures that each layer is simplified to valid 2D spatial features, reducing file size and improving computational efficiency.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool     <- st_zm(preschool)\neldercare     <- st_zm(eldercare)\nhawker        <- st_zm(hawker)\nparks         <- st_zm(parks)\nsupermarkets  <- st_zm(supermarkets)\nmrt_station   <- st_zm(mrt_station)\nbus_stop      <- st_zm(bus_stop)\nkindergartens <- st_zm(kindergartens)\nchildcare     <- st_zm(childcare)\nclinics       <- st_zm(clinics)\nprimary_schools <- st_zm(primary_schools)\ngood_primary_schools <- st_zm(good_primary_schools)\nshopping      <- st_zm(shopping)\n```\n:::\n\n\n## 2.4 Attribute Reduction\n\nAfter simplifying geometries, only essential columns were retained for each spatial dataset using the select() function. Non-essential metadata fields were removed, keeping only key identifiers and geometry information. This streamlines the data for subsequent spatial joins, distance calculations, and modelling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool     <- preschool %>% select(c(1))\neldercare     <- eldercare %>% select(c(1))\nhawker        <- hawker %>% select(c(1))\nparks         <- parks %>% select(c(1))\nsupermarkets  <- supermarkets %>% select(c(1))\nmrt_station   <- mrt_station %>% select(c(1))\nbus_stop      <- bus_stop %>% select(c(1))\nkindergartens <- kindergartens %>% select(c(1))\nchildcare     <- childcare %>% select(c(1))\nclinics       <- clinics %>% select(c(1))\nshopping      <- shopping %>% select(c(1))\nschools <- schools %>% select(c(1))\nprimary_schools       <- primary_schools %>% select(c(1))\ngood_primary_schools  <- good_primary_schools %>% select(c(1))\n```\n:::\n\n\n## 2.5 Validate Geometries\n\nUse the st_is_valid() function to check the MPSZ data and delete the invalid geometries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(which(st_is_valid(mpsz) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_make_valid(mpsz)\n```\n:::\n\n\n## 2.6 Geometry Validation Across Layers\n\nA consistency check was conducted on all imported spatial datasets to confirm their geometric validity. This process helps identify potential boundary or coordinate issues before performing spatial joins and analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(which(st_is_valid(HDBresale) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(mpsz) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(preschool) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(eldercare) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(hawker) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(parks) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(supermarkets) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(mrt_station) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(bus_stop) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(kindergartens) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(childcare) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(clinics) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(schools) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(primary_schools) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(good_primary_schools) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(cbd) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(which(st_is_valid(shopping) == FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n## 2.7 MRT Geometry Correction\n\nThe MRT station dataset contained non-point geometries (e.g., polygons or mixed types). To correct this, the geometries were converted to point representations using a custom safe_point() function, which extracts the centroid or bounding box midpoint when errors occur.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsf_use_s2(FALSE)\n\nmrt_station <- st_transform(mrt_station, 3414)\nmrt_station <- st_zm(mrt_station, drop = TRUE, what = \"ZM\")\n\nmrt_station <- st_collection_extract(mrt_station, \"POLYGON\", warn = FALSE)\nmrt_station <- mrt_station[!st_is_empty(mrt_station), ]\n\nsafe_point <- function(g) {\n  p <- try(st_point_on_surface(g), silent = TRUE)\n  if (inherits(p, \"try-error\")) {\n    bb <- st_bbox(g)\n    st_point(c((bb[\"xmin\"] + bb[\"xmax\"]) / 2,\n               (bb[\"ymin\"] + bb[\"ymax\"]) / 2))\n  } else {\n    st_geometry(p)[[1]]\n  }\n}\n\npts <- st_sfc(lapply(st_geometry(mrt_station), safe_point), crs = st_crs(mrt_station))\nmrt_station <- st_set_geometry(mrt_station, pts)\nmrt_station <- st_cast(mrt_station, \"POINT\", warn = FALSE)\n\n# check result\nunique(st_geometry_type(mrt_station))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] POINT\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n:::\n\n\n## 2.8 Remove Out-of-Bound Features\n\nI noticed that there were outliers in the data, so we removed them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparks <- st_join(\n  parks, mpsz, \n  join = st_within, \n  left = FALSE)\n\nbus_stop <- st_join(\n  bus_stop, mpsz, \n  join = st_within, \n  left = FALSE)\n```\n:::\n\n\n# 3 Initial EDA Visualisation\n\nWe can examine the following visualizations to understand the distribution of various datasets and gain deeper insights into the data. Overall, the distributions appear reasonable, with no outliers or values beyond expected spatial boundaries.\n\n::: panel-tabset\n# HDBresale\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(HDBresale) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n# MPSZ\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha=0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\n# preschool\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(preschool) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n# eldercare\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(eldercare) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n# hawker\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(hawker) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n# parks\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(parks) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n# supermarkets\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(supermarkets) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n# MRT station\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(mrt_station) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n# bus stop\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(bus_stop) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\n# kindergartens\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(kindergartens) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n\n# childcare\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(childcare) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\n# clinics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(clinics) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\n# schools\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(schools) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n\n# primary schools\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(primary_schools) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n\n# good school\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(good_primary_schools) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n:::\n\n\n# CBD\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(cbd) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-69-1.png){width=672}\n:::\n:::\n\n\n# Shopping Mall\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(shopping) +\n  tm_symbols(col = \"red\", size = 0.1, shape = 19, border.col = NA) +\n  tm_layout(frame = FALSE, legend.show = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-70-1.png){width=672}\n:::\n:::\n\n:::\n\n# 4 Data Wrangling\n\n## 4.1 Structural factors\n\nThis step converts the month variable into proper Date format for time-based filtering and analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- HDBresale %>%\n  mutate(month = as.Date(paste0(month, \"-01\")))\n```\n:::\n\n\nExtracts numeric values of years and months from the remaining_lease field and computes the total remaining lease in months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- HDBresale %>%\n  mutate(\n    years = as.numeric(str_extract(remaining_lease, \"\\\\d+(?=\\\\s*years)\")),\n    months = as.numeric(str_extract(remaining_lease, \"\\\\d+(?=\\\\s*months)\")),\n    months = replace_na(months, 0),  \n    remaining_lease_mths = years * 12 + months\n  ) %>%\n  select(-years, -months)\n```\n:::\n\n\nParses the storey_range column to obtain the lower and upper floor levels, then calculates the average storey height (storey_mean).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- HDBresale %>%\n  mutate(\n    storey_low  = as.numeric(str_extract(storey_range, \"^[0-9]+\")),\n    storey_high = as.numeric(str_extract(storey_range, \"[0-9]+$\")),\n    storey_mean = (storey_low + storey_high) / 2\n  )\n```\n:::\n\n\nCalculates the age_of_unit by subtracting the lease commencement year from 2025.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- HDBresale %>%\n  mutate(age_of_unit = 2025 - lease_commence_date)\n```\n:::\n\n\nSelects only relevant structural and spatial variables for subsequent analysis and model building.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- HDBresale %>%\n  select(\n    month,\n    town,\n    block,\n    street_name,\n    flat_type,\n    floor_area_sqm,\n    storey_mean,\n    remaining_lease_mths,\n    age_of_unit,\n    resale_price,\n    geometry\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14,737\nColumns: 11\n$ month                <date> 2024-07-01, 2024-07-01, 2024-07-01, 2024-07-01, …\n$ town                 <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO…\n$ block                <chr> \"335\", \"333\", \"226\", \"336\", \"303\", \"226\", \"337\", …\n$ street_name          <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 1\", \"ANG MO K…\n$ flat_type            <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\",…\n$ floor_area_sqm       <dbl> 91, 93, 91, 91, 97, 92, 91, 97, 94, 88, 102, 91, …\n$ storey_mean          <dbl> 2, 2, 8, 2, 11, 11, 2, 5, 8, 20, 8, 8, 11, 5, 26,…\n$ remaining_lease_mths <dbl> 680, 668, 631, 680, 621, 631, 680, 620, 1044, 104…\n$ age_of_unit          <dbl> 43, 44, 47, 43, 48, 47, 43, 48, 13, 13, 32, 43, 1…\n$ resale_price         <dbl> 528888, 500000, 540000, 500000, 620000, 570000, 5…\n$ geometry             <POINT [m]> POINT (29933.3 38362.35), POINT (30045.48 3…\n```\n\n\n:::\n:::\n\n\n## 4.2 Location factors\n\n### 4.2.1 Calculate Nearest Distances\n\nThis step computes the Euclidean distance (in meters) from each HDB resale unit to the nearest key amenities and facilities, including the CBD, eldercare centres, hawker centres, MRT stations, parks, good primary schools, shopping malls, supermarkets, and clinics. The results are stored as new distance variables (e.g., dist_cbd, dist_mrt) to quantify locational accessibility.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CBD\ndis_cbd <- st_nearest_feature(HDBresale, cbd)\nHDBresale$dist_cbd <- as.numeric(st_distance(HDBresale, cbd[dis_cbd, ], by_element = TRUE))\n\n# Eldercare\ndis_elder <- st_nearest_feature(HDBresale, eldercare)\nHDBresale$dist_eldercare <- as.numeric(st_distance(HDBresale, eldercare[dis_elder, ], by_element = TRUE))\n\n# Hawker\ndis_hawker <- st_nearest_feature(HDBresale, hawker)\nHDBresale$dist_hawker <- as.numeric(st_distance(HDBresale, hawker[dis_hawker, ], by_element = TRUE))\n\n# MRT station\ndis_mrt <- st_nearest_feature(HDBresale, mrt_station)\nHDBresale$dist_mrt <- as.numeric(st_distance(HDBresale, mrt_station[dis_mrt, ], by_element = TRUE))\n\n# parks\ndis_parks <- st_nearest_feature(HDBresale, parks)\nHDBresale$dist_park <- as.numeric(st_distance(HDBresale, parks[dis_parks, ], by_element = TRUE))\n\n# Good primary schools\ndis_goodps <- st_nearest_feature(HDBresale, good_primary_schools)\nHDBresale$dist_good_primary <- as.numeric(st_distance(HDBresale, good_primary_schools[dis_goodps, ], by_element = TRUE))\n\n# Shopping malls\ndis_mall <- st_nearest_feature(HDBresale, shopping)\nHDBresale$dist_mall <- as.numeric(st_distance(HDBresale, shopping[dis_mall, ], by_element = TRUE))\n\n# Supermarkets\ndis_super <- st_nearest_feature(HDBresale, supermarkets)\nHDBresale$dist_supermarket <- as.numeric(st_distance(HDBresale, supermarkets[dis_super, ], by_element = TRUE))\n\n# Clinics\ndis_clinic <- st_nearest_feature(HDBresale, clinics)\nHDBresale$dist_clinic <- as.numeric(st_distance(HDBresale, clinics[dis_clinic, ], by_element = TRUE))\n```\n:::\n\n\n### 4.2.2 Count Nearby Amenities\n\nUsing spatial proximity analysis, this step counts the number of nearby facilities within a specified radius of each HDB unit. For example, the number of kindergartens, childcare centres, bus stops, and preschools within 350 meters, and the number of primary schools and all schools within 1 kilometer. These counts serve as accessibility indicators reflecting the neighbourhood environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_kindergartens_350m <- st_is_within_distance(HDBresale, kindergartens,  dist = 350)\nwithin_childcare_350m     <- st_is_within_distance(HDBresale, childcare,      dist = 350)\nwithin_bus_350m           <- st_is_within_distance(HDBresale, bus_stop,       dist = 350)\nwithin_preschool_350m     <- st_is_within_distance(HDBresale, preschool,      dist = 350)\nwithin_primary_1km        <- st_is_within_distance(HDBresale, primary_schools,dist = 1000)\nwithin_schools_1km        <- st_is_within_distance(HDBresale, schools,        dist = 1000)\n\nHDBresale <- HDBresale %>%\n  mutate(\n    n_kindergartens_350m = map_int(within_kindergartens_350m, length),\n    n_childcare_350m     = map_int(within_childcare_350m,     length),\n    n_bus_350m           = map_int(within_bus_350m,           length),\n    n_preschool_350m     = map_int(within_preschool_350m,     length)\n  )\n\nHDBresale <- HDBresale %>%\n  mutate(\n    n_primary_1km = map_int(within_primary_1km, length),\n    n_schools_1km = map_int(within_schools_1km, length)\n  )\n```\n:::\n\n\n# 5 Exploratory Data Analysis – Variable Distributions\n\n## 5.1 Overview for data\n\nThis dataset contains 14,737 observations of resale transactions for 4 room HDB flats from July 2024 to September 2025. The resale prices range from 300,000 Singapore dollars to 1,518,000 Singapore dollars, with an average floor area of 94.83 square meters and an average building age of 23 years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14,737\nColumns: 26\n$ month                <date> 2024-07-01, 2024-07-01, 2024-07-01, 2024-07-01, …\n$ town                 <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO…\n$ block                <chr> \"335\", \"333\", \"226\", \"336\", \"303\", \"226\", \"337\", …\n$ street_name          <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 1\", \"ANG MO K…\n$ flat_type            <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\",…\n$ floor_area_sqm       <dbl> 91, 93, 91, 91, 97, 92, 91, 97, 94, 88, 102, 91, …\n$ storey_mean          <dbl> 2, 2, 8, 2, 11, 11, 2, 5, 8, 20, 8, 8, 11, 5, 26,…\n$ remaining_lease_mths <dbl> 680, 668, 631, 680, 621, 631, 680, 620, 1044, 104…\n$ age_of_unit          <dbl> 43, 44, 47, 43, 48, 47, 43, 48, 13, 13, 32, 43, 1…\n$ resale_price         <dbl> 528888, 500000, 540000, 500000, 620000, 570000, 5…\n$ geometry             <POINT [m]> POINT (29933.3 38362.35), POINT (30045.48 3…\n$ dist_cbd             <dbl> 8493.766, 8280.433, 9185.376, 8528.406, 8934.515,…\n$ dist_eldercare       <dbl> 334.27019, 433.83460, 397.61080, 214.39384, 292.3…\n$ dist_hawker          <dbl> 289.98144, 424.99822, 132.00515, 398.27582, 435.3…\n$ dist_mrt             <dbl> 758.5365, 983.4842, 520.9397, 747.1861, 606.9078,…\n$ dist_park            <dbl> 360.0341, 327.9909, 356.4783, 470.0032, 708.2193,…\n$ dist_good_primary    <dbl> 1987.8236, 2080.3690, 991.5717, 2114.5860, 1517.7…\n$ dist_mall            <dbl> 709.4343, 942.6622, 1132.0243, 723.6642, 457.0475…\n$ dist_supermarket     <dbl> 349.25330, 468.66713, 186.27015, 237.72203, 350.3…\n$ dist_clinic          <dbl> 9.399557e+01, 1.415401e+02, 1.011686e+02, 1.53442…\n$ n_kindergartens_350m <int> 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0…\n$ n_childcare_350m     <int> 2, 1, 5, 3, 7, 5, 3, 7, 6, 6, 4, 3, 2, 5, 5, 4, 2…\n$ n_bus_350m           <int> 8, 7, 7, 6, 7, 7, 7, 7, 4, 4, 4, 7, 5, 6, 4, 4, 5…\n$ n_preschool_350m     <int> 2, 1, 7, 3, 8, 7, 3, 8, 7, 7, 5, 3, 2, 6, 6, 5, 2…\n$ n_primary_1km        <int> 3, 2, 2, 3, 3, 2, 3, 3, 2, 2, 2, 3, 2, 3, 2, 2, 2…\n$ n_schools_1km        <int> 4, 3, 7, 4, 6, 7, 4, 6, 5, 5, 6, 4, 5, 6, 5, 6, 5…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     month                town              block           street_name       \n Min.   :2024-07-01   Length:14737       Length:14737       Length:14737      \n 1st Qu.:2024-10-01   Class :character   Class :character   Class :character  \n Median :2025-02-01   Mode  :character   Mode  :character   Mode  :character  \n Mean   :2025-01-26                                                           \n 3rd Qu.:2025-06-01                                                           \n Max.   :2025-09-01                                                           \n  flat_type         floor_area_sqm    storey_mean     remaining_lease_mths\n Length:14737       Min.   : 74.00   Min.   : 2.000   Min.   : 485.0      \n Class :character   1st Qu.: 92.00   1st Qu.: 5.000   1st Qu.: 753.0      \n Mode  :character   Median : 93.00   Median : 8.000   Median : 914.0      \n                    Mean   : 94.83   Mean   : 9.232   Mean   : 918.5      \n                    3rd Qu.:100.00   3rd Qu.:11.000   3rd Qu.:1084.0      \n                    Max.   :135.00   Max.   :50.000   Max.   :1144.0      \n  age_of_unit     resale_price              geometry        dist_cbd    \n Min.   : 4.00   Min.   : 300000   POINT        :14737   Min.   : 1023  \n 1st Qu.: 9.00   1st Qu.: 552000   epsg:3414    :    0   1st Qu.: 9996  \n Median :23.00   Median : 620000   +proj=tmer...:    0   Median :13359  \n Mean   :22.92   Mean   : 661081                         Mean   :12563  \n 3rd Qu.:37.00   3rd Qu.: 713888                         3rd Qu.:15698  \n Max.   :58.00   Max.   :1518000                         Max.   :19874  \n dist_eldercare       dist_hawker         dist_mrt         dist_park      \n Min.   :   0.0004   Min.   :  25.35   Min.   :  20.88   Min.   :  63.81  \n 1st Qu.: 337.5461   1st Qu.: 377.90   1st Qu.: 317.29   1st Qu.: 455.97  \n Median : 660.4340   Median : 647.45   Median : 548.91   Median : 667.03  \n Mean   : 822.7593   Mean   : 732.41   Mean   : 618.86   Mean   : 756.47  \n 3rd Qu.:1144.2391   3rd Qu.: 959.11   3rd Qu.: 835.76   3rd Qu.: 980.30  \n Max.   :3301.6373   Max.   :2500.14   Max.   :2159.69   Max.   :2210.33  \n dist_good_primary    dist_mall         dist_supermarket     dist_clinic       \n Min.   :   74.37   Min.   :1.190e-03   Min.   :2.600e-04   Min.   :  0.00001  \n 1st Qu.: 1345.89   1st Qu.:3.947e+02   1st Qu.:1.777e+02   1st Qu.:111.99873  \n Median : 2456.41   Median :6.206e+02   Median :2.751e+02   Median :172.37676  \n Mean   : 3543.80   Mean   :6.960e+02   Mean   :3.033e+02   Mean   :188.62361  \n 3rd Qu.: 4837.89   3rd Qu.:9.301e+02   3rd Qu.:3.902e+02   3rd Qu.:243.46665  \n Max.   :11490.86   Max.   :2.322e+03   Max.   :1.415e+03   Max.   :808.33274  \n n_kindergartens_350m n_childcare_350m   n_bus_350m     n_preschool_350m\n Min.   :0.0000       Min.   : 0.000   Min.   : 0.000   Min.   : 0.000  \n 1st Qu.:0.0000       1st Qu.: 3.000   1st Qu.: 6.000   1st Qu.: 3.000  \n Median :1.0000       Median : 4.000   Median : 8.000   Median : 5.000  \n Mean   :0.9339       Mean   : 4.682   Mean   : 8.008   Mean   : 5.493  \n 3rd Qu.:1.0000       3rd Qu.: 6.000   3rd Qu.:10.000   3rd Qu.: 7.000  \n Max.   :8.0000       Max.   :22.000   Max.   :19.000   Max.   :25.000  \n n_primary_1km   n_schools_1km   \n Min.   :0.000   Min.   : 0.000  \n 1st Qu.:2.000   1st Qu.: 4.000  \n Median :3.000   Median : 5.000  \n Mean   :3.049   Mean   : 5.239  \n 3rd Qu.:4.000   3rd Qu.: 7.000  \n Max.   :9.000   Max.   :14.000  \n```\n\n\n:::\n:::\n\n\n## 5.2 EDA for Structural factors\n\nThe distribution of resale prices is positively skewed, with most transactions falling within the SGD 500,000–800,000 range, indicating the presence of a small number of high-priced units. The floor area is relatively concentrated between 90 and 100 square meters, suggesting limited variation in unit size across the sample. The storey level also exhibits a right-skewed pattern, with the majority of units located below the 20th floor, reflecting the prevalence of low- to mid-rise flats. The remaining lease is generally long, mostly ranging from 5 to 10 years, implying that the dataset comprises a large proportion of newer housing units.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(HDBresale, aes(x = resale_price)) +\n  geom_histogram(bins = 20, fill = \"lightblue\", color = \"black\") +\n  theme_minimal()\n\np2 <- ggplot(HDBresale, aes(x = floor_area_sqm)) +\n  geom_histogram(bins = 20, fill = \"lightgreen\", color = \"black\") +\n  theme_minimal()\n\np3 <- ggplot(HDBresale, aes(x = storey_mean)) +\n  geom_histogram(bins = 20, fill = \"orange\", color = \"black\") +\n  theme_minimal()\n\np4 <- ggplot(HDBresale, aes(x = remaining_lease_mths)) +\n  geom_histogram(bins = 20, fill = \"plum\", color = \"black\") +\n  theme_minimal()\n\np5 <- ggplot(HDBresale, aes(x = age_of_unit)) +\n  geom_histogram(bins = 20, fill = \"salmon\", color = \"black\") +\n  theme_minimal()\n\n(p1) /\n(p2 + p3) /\n(p4 + p5)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-81-1.png){width=1152}\n:::\n:::\n\n\n## 5.3 EDA for Location factors\n\nFrom the visualization results, most accessibility variables (such as dist_eldercare, dist_hawker, dist_mrt, dist_park, dist_mall, dist_supermarket, and dist_clinic) exhibit approximately normal or mildly right-skewed distributions, indicating relatively balanced variations in the distance between housing units and nearby facilities.\n\nThe variable dist_cbd shows a more pronounced right-skewed pattern, suggesting that most units are located farther from the Central Business District, with only a few situated close to it.\n\nMeanwhile, facility count variables (such as n_kindergartens_350m, n_preschool_350m, and n_primary_1km) display clear discrete and skewed distributions. In particular, preschool-related facilities are concentrated at lower counts, implying that most residential areas have relatively low educational facility density.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlocation_factors <- c(\n  \"dist_cbd\",\"dist_eldercare\",\"dist_hawker\",\"dist_mrt\",\"dist_park\",\n  \"dist_good_primary\",\"dist_mall\",\"dist_supermarket\",\"dist_clinic\",\n  \"n_kindergartens_350m\",\"n_childcare_350m\",\"n_bus_350m\",\n  \"n_preschool_350m\",\"n_primary_1km\",\"n_schools_1km\"\n)\n\nplots <- lapply(location_factors, function(v) {\n  ggplot(HDBresale, aes_string(x = v)) +\n    geom_histogram(bins = 20, color = \"black\", fill = \"lightblue\") +\n    labs(title = v, x = NULL, y = NULL) +\n    theme_minimal() +\n    theme(\n      plot.title = element_text(size = 9, hjust = 0.5),\n      axis.text = element_text(size = 6)\n    )\n})\n\nEDA_Location <- wrap_plots(plots, ncol = 3) +\n  plot_annotation(title = \"EDA of Location & Accessibility Factors\")\n\nEDA_Location\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-82-1.png){width=1152}\n:::\n:::\n\n\n## 5.4 Geospatial EDA for Resale Price\n\nThe resale prices exhibit a clear spatial differentiation pattern. High-priced units (in dark blue) are mainly concentrated in central and mature estates, such as Queenstown, Bishan, Tiong Bahru, and the areas surrounding the city center, where transportation accessibility and amenities are superior, and proximity to the CBD adds to the value. Overall, resale prices tend to be higher in the central and northeastern regions of Singapore.\n\nIn contrast, peripheral regions such as Woodlands, Punggol, Yishun, and Tampines show lower prices (in light blue), reflecting the significant influence of location and neighborhood amenities on HDB resale values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_sample <- HDBresale %>% sample_frac(0.5) \n\ntm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\ntm_shape(HDB_sample) +  \n  tm_dots(col = \"resale_price\", size = 0.4, alpha = 0.15, style = \"quantile\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-83-1.png){width=1152}\n:::\n:::\n\n\n# 6 Multicollinearity Analysis\n\nUse the ggcorrmat() function to detect potential multicollinearity among the independent variables to ensure the stability and interpretability of the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_nogeo <- HDBresale %>%\n  st_drop_geometry()\nggcorrmat(hdb_nogeo, names(hdb_nogeo))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-84-1.png){width=1152}\n:::\n:::\n\n\nBased on the correlation analysis results, n_primary_1km and n_schools_1km, age_of_unit and remaining_lease_mths, as well as n_preschool_350m and n_childcare_350m, exhibit strong correlations with absolute values exceeding 0.8. Therefore, the variables n_schools_1km, age_of_unit, and n_preschool_350m were excluded from subsequent analysis to mitigate multicollinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nre_hdb_nogeo <- HDBresale %>%\n  st_drop_geometry() %>% \n  select(\n    -n_schools_1km,\n    -age_of_unit,\n    -n_preschool_350m\n  )\nggcorrmat(re_hdb_nogeo, names(re_hdb_nogeo))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-85-1.png){width=1152}\n:::\n:::\n\n\n# 7 Regression Model\n\n## 7.1 split Training data and Test data\n\nTo meet the assignment requirement, the dataset was divided into two temporal subsets: a training set (July 2024 – June 2025) used to calibrate the predictive model, and a test set (July – September 2025) used to evaluate its predictive performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale_train <- HDBresale %>%\n  filter(month >= as.Date(\"2024-07-01\") & month <= as.Date(\"2025-06-30\"))\n\nhdb_resale_test <- HDBresale %>%\n  filter(month >= as.Date(\"2025-07-01\") & month <= as.Date(\"2025-09-30\"))\n```\n:::\n\n\n## 7.2 Calibration of Multiple Linear Regression (MLR) Model\n\nIn this stage, a Multiple Linear Regression (MLR) model was calibrated to examine the relationship between HDB resale prices and various structural as well as locational factors.\n\nIn the initial regression, all explanatory variables were included. The model achieved a strong overall fit with an R² of 0.796, indicating that approximately 79.6% of the variation in resale prices can be explained by the included predictors. All coefficients were statistically significant (p \\< 0.05).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale_mlr <- lm(\n  formula = resale_price ~ \n    dist_cbd +\n    dist_eldercare +\n    dist_hawker +\n    dist_mrt +\n    dist_park +\n    dist_good_primary +\n    dist_supermarket +\n    dist_clinic +\n    n_kindergartens_350m+\n    dist_mall +\n    n_childcare_350m +\n    n_bus_350m +\n    n_primary_1km +\n    floor_area_sqm +\n    storey_mean +\n    remaining_lease_mths,\n  data = hdb_resale_train\n)\n\nols_regress(resale_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                              Model Summary                                \n--------------------------------------------------------------------------\nR                           0.892       RMSE                    70041.452 \nR-Squared                   0.796       MSE                4905805050.521 \nAdj. R-Squared              0.796       Coef. Var                  10.668 \nPred R-Squared              0.796       AIC                    293806.245 \nMAE                     54279.825       SBC                    293938.827 \n--------------------------------------------------------------------------\n RMSE: Root Mean Square Error \n MSE: Mean Square Error \n MAE: Mean Absolute Error \n AIC: Akaike Information Criteria \n SBC: Schwarz Bayesian Criteria \n\n                                     ANOVA                                       \n--------------------------------------------------------------------------------\n                    Sum of                                                      \n                   Squares           DF       Mean Square       F          Sig. \n--------------------------------------------------------------------------------\nRegression    2.239683e+14           16      1.399802e+13    2849.205    0.0000 \nResidual       5.72998e+13        11663    4912955756.674                       \nTotal         2.812681e+14        11679                                         \n--------------------------------------------------------------------------------\n\n                                             Parameter Estimates                                              \n-------------------------------------------------------------------------------------------------------------\n               model          Beta    Std. Error    Std. Beta       t        Sig          lower        upper \n-------------------------------------------------------------------------------------------------------------\n         (Intercept)     74233.713     11607.042                   6.396    0.000     51481.968    96985.459 \n            dist_cbd       -21.266         0.263       -0.597    -80.924    0.000       -21.781      -20.750 \n      dist_eldercare       -12.214         1.170       -0.050    -10.440    0.000       -14.507       -9.921 \n         dist_hawker       -27.139         1.523       -0.081    -17.821    0.000       -30.124      -24.154 \n            dist_mrt       -46.521         1.962       -0.114    -23.708    0.000       -50.368      -42.675 \n           dist_park       -13.289         1.798       -0.035     -7.390    0.000       -16.813       -9.764 \n   dist_good_primary         4.723         0.326        0.091     14.492    0.000         4.084        5.361 \n    dist_supermarket        17.647         4.156        0.020      4.246    0.000         9.501       25.794 \n         dist_clinic       -14.099         6.652       -0.010     -2.119    0.034       -27.138       -1.060 \nn_kindergartens_350m      8127.668       728.936        0.055     11.150    0.000      6698.831     9556.504 \n           dist_mall       -19.543         1.949       -0.050    -10.027    0.000       -23.364      -15.723 \n    n_childcare_350m     -1595.990       351.970       -0.024     -4.534    0.000     -2285.909     -906.070 \n          n_bus_350m      1024.652       247.208        0.019      4.145    0.000       540.084     1509.220 \n       n_primary_1km    -10059.869       515.599       -0.101    -19.511    0.000    -11070.529    -9049.209 \n      floor_area_sqm      4764.590       104.796        0.203     45.466    0.000      4559.173     4970.007 \n         storey_mean      5785.229       113.095        0.236     51.154    0.000      5563.545     6006.913 \nremaining_lease_mths       468.454         4.308        0.510    108.743    0.000       460.010      476.898 \n-------------------------------------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n## 7.3 Multicollinearity Diagnostics\n\nThe VIF results indicate that all variables have VIF values below 5, suggesting no severe multicollinearity issue in the model. Although dist_cbd shows the highest VIF (3.07), it remains within the acceptable range, confirming that the independent variables are not excessively correlated and the model estimates are stable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_vif_tol(resale_mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Variables Tolerance      VIF\n1              dist_cbd 0.3212642 3.112703\n2        dist_eldercare 0.7673807 1.303134\n3           dist_hawker 0.8508351 1.175316\n4              dist_mrt 0.7556456 1.323372\n5             dist_park 0.7694455 1.299637\n6     dist_good_primary 0.4471777 2.236247\n7      dist_supermarket 0.7873602 1.270067\n8           dist_clinic 0.8369023 1.194883\n9  n_kindergartens_350m 0.7221108 1.384829\n10            dist_mall 0.6959377 1.436910\n11     n_childcare_350m 0.6345947 1.575809\n12           n_bus_350m 0.8419818 1.187674\n13        n_primary_1km 0.6475825 1.544205\n14       floor_area_sqm 0.8723331 1.146351\n15          storey_mean 0.8190973 1.220856\n16 remaining_lease_mths 0.7943108 1.258953\n```\n\n\n:::\n:::\n\n\n## 7.4 Test for Spatial Autocorrelation\n\nThe residual map indicate a significant spatial autocorrelation in the model residuals. Clusters of overestimation (green) and underestimation (purple) can be observed in several regions, particularly in the central and northeastern parts of Singapore.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr_res <- as.data.frame(resale_mlr$residuals)\n\nresale_res <- cbind(hdb_resale_train,\n                    mlr_res) %>%\n  rename(MLR_RES = resale_mlr.residuals)\n\ntm_shape(mpsz)+\n  tm_polygons(col = \"white\") +\ntm_shape(resale_res) +  \n  tm_dots(col = \"MLR_RES\",\n          alpha = 0.6,\n          style=\"quantile\") +\n  tm_layout(main.title = \"Multiple Linear Regression Residuals\",     \n            main.title.position = \"center\",\n            main.title.size = 1)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-89-1.png){width=672}\n:::\n:::\n\n\n## 7.5 Moran’s I test\n\nThe Moran’s I value of 0.327 with a p-value \\< 0.001 confirms that the residuals are not randomly distributed but exhibit strong spatial clustering. This suggests that the traditional MLR model fails to fully account for spatial heterogeneity, implying the need for geographically weighted models such as GWR or GWRF for improved performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale_sp <- as_Spatial(resale_res)\n\nnb <- dnearneigh(coordinates(resale_sp), 0, 1500, longlat = FALSE)\nnb_lw <- nb2listw(nb, style = 'W')\n\nlm.morantest(resale_mlr, nb_lw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGlobal Moran I for regression residuals\n\ndata:  \nmodel: lm(formula = resale_price ~ dist_cbd + dist_eldercare +\ndist_hawker + dist_mrt + dist_park + dist_good_primary +\ndist_supermarket + dist_clinic + n_kindergartens_350m + dist_mall +\nn_childcare_350m + n_bus_350m + n_primary_1km + floor_area_sqm +\nstorey_mean + remaining_lease_mths, data = hdb_resale_train)\nweights: nb_lw\n\nMoran I statistic standard deviate = 489.56, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nObserved Moran I      Expectation         Variance \n    3.276029e-01    -5.990492e-04     4.494389e-07 \n```\n\n\n:::\n:::\n\n\n## 7.6 Geospatial weighted regression model\n\n### 7.6.1 GWR Bandwidth Selection\n\nUsing the same variables as in the previous MLR, the optimal adaptive bandwidth is determined through cross-validation under the Gaussian kernel function. This bandwidth determines the spatial scale for local model fitting and ensures the optimal balance between bias and variance in spatial prediction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- bw.gwr(formula = resale_price ~ \n    dist_cbd +\n    dist_eldercare +\n    dist_hawker +\n    dist_mrt +\n    dist_park +\n    dist_good_primary +\n    dist_supermarket + \n    n_kindergartens_350m+\n    dist_mall +\n    n_childcare_350m +\n    n_bus_350m +\n     n_primary_1km+\n    floor_area_sqm +\n    storey_mean +\n    remaining_lease_mths,\n                      data=resale_sp, \n                      approach=\"CV\", \n                      kernel=\"gaussian\", \n                      adaptive=TRUE, \n                      longlat=FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(bw_adaptive, \"data/rds/bw_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nAfter calculation, the optimal bandwidth is 78.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 78\n```\n\n\n:::\n:::\n\n\n### 7.6.2 Geospatial weighted regression model\n\nIn this section, a Geographically Weighted Regression (GWR) model was calibrated to address the spatial autocorrelation issue observed in the MLR residuals. Unlike the global MLR model, which assumes that the relationship between explanatory variables and housing prices is spatially constant across Singapore, the GWR model allows these relationships to vary locally by assigning different parameter estimates at each spatial location. This approach captures the spatial heterogeneity in housing market dynamics more effectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- gwr.basic(\n  formula = resale_price ~ \n    dist_cbd +\n    dist_eldercare +\n    dist_hawker +\n    dist_mrt +\n    dist_park +\n    dist_good_primary +\n    dist_supermarket + \n    n_kindergartens_350m +\n    dist_mall +\n    n_childcare_350m +\n    n_bus_350m +\n     n_primary_1km +\n    floor_area_sqm +\n    storey_mean +\n    remaining_lease_mths,\n  data    = resale_sp,\n  bw      = bw_adaptive, \n  kernel  = \"gaussian\",\n  adaptive = TRUE,\n  longlat = FALSE\n)\n\ngwr_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-16 15:10:19.933092 \n   Call:\n   gwr.basic(formula = resale_price ~ dist_cbd + dist_eldercare + \n    dist_hawker + dist_mrt + dist_park + dist_good_primary + \n    dist_supermarket + n_kindergartens_350m + dist_mall + n_childcare_350m + \n    n_bus_350m + n_primary_1km + floor_area_sqm + storey_mean + \n    remaining_lease_mths, data = resale_sp, bw = bw_adaptive, \n    kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  dist_cbd dist_eldercare dist_hawker dist_mrt dist_park dist_good_primary dist_supermarket n_kindergartens_350m dist_mall n_childcare_350m n_bus_350m n_primary_1km floor_area_sqm storey_mean remaining_lease_mths\n   Number of data points: 11680\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-270583  -46487    1739   43161  427961 \n\n   Coefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)           7.292e+04  1.159e+04   6.291 3.27e-10 ***\n   dist_cbd             -2.129e+01  2.625e-01 -81.099  < 2e-16 ***\n   dist_eldercare       -1.234e+01  1.169e+00 -10.561  < 2e-16 ***\n   dist_hawker          -2.733e+01  1.520e+00 -17.974  < 2e-16 ***\n   dist_mrt             -4.679e+01  1.958e+00 -23.888  < 2e-16 ***\n   dist_park            -1.342e+01  1.797e+00  -7.465 8.94e-14 ***\n   dist_good_primary     4.717e+00  3.259e-01  14.474  < 2e-16 ***\n   dist_supermarket      1.511e+01  3.980e+00   3.796 0.000148 ***\n   n_kindergartens_350m  8.042e+03  7.279e+02  11.047  < 2e-16 ***\n   dist_mall            -1.915e+01  1.940e+00  -9.868  < 2e-16 ***\n   n_childcare_350m     -1.558e+03  3.516e+02  -4.431 9.45e-06 ***\n   n_bus_350m            1.076e+03  2.461e+02   4.371 1.25e-05 ***\n   n_primary_1km        -1.002e+04  5.154e+02 -19.448  < 2e-16 ***\n   floor_area_sqm        4.747e+03  1.045e+02  45.437  < 2e-16 ***\n   storey_mean           5.779e+03  1.131e+02  51.108  < 2e-16 ***\n   remaining_lease_mths  4.697e+02  4.267e+00 110.069  < 2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 70100 on 11664 degrees of freedom\n   Multiple R-squared: 0.7962\n   Adjusted R-squared: 0.7959 \n   F-statistic:  3038 on 15 and 11664 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 5.732187e+13\n   Sigma(hat): 70060.94\n   AIC:  293808.7\n   AICc:  293808.8\n   BIC:  282413.2\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 78 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                               Min.     1st Qu.      Median     3rd Qu.\n   Intercept            -2.9775e+07 -3.4313e+05  6.2753e+04  1.1754e+06\n   dist_cbd             -4.1600e+03 -1.0357e+02 -1.4950e+01  2.3633e+01\n   dist_eldercare       -2.0941e+04 -2.3199e+01  8.5210e+00  4.1065e+01\n   dist_hawker          -8.4552e+03 -5.6969e+01 -1.5310e+01  2.9956e+01\n   dist_mrt             -2.3594e+03 -1.0425e+02 -5.7709e+01 -1.8041e+01\n   dist_park            -1.1250e+03 -3.8731e+01 -4.0386e+00  2.5727e+01\n   dist_good_primary    -9.3031e+03 -4.3717e+01 -5.1789e-01  9.5845e+01\n   dist_supermarket     -5.8279e+03 -4.5773e+01 -4.6146e+00  2.8346e+01\n   n_kindergartens_350m -2.1741e+06 -7.0947e+03 -9.8102e+02  3.4229e+03\n   dist_mall            -4.7636e+03 -6.5928e+01 -1.7755e+01  1.7746e+01\n   n_childcare_350m     -6.0432e+05 -1.4276e+03  6.6240e+01  2.8933e+03\n   n_bus_350m           -2.1097e+05 -1.7379e+03  1.6022e+01  1.4679e+03\n   n_primary_1km        -2.2946e+06 -6.1236e+03 -5.0735e+02  4.4403e+03\n   floor_area_sqm       -1.8053e+04  2.4831e+03  3.2619e+03  5.0574e+03\n   storey_mean           2.0450e+03  3.8979e+03  4.8432e+03  5.5401e+03\n   remaining_lease_mths -4.8857e+03  3.1548e+02  4.1377e+02  6.5863e+02\n                              Max.\n   Intercept            41349590.2\n   dist_cbd                 7718.0\n   dist_eldercare           3098.1\n   dist_hawker              1646.2\n   dist_mrt                 6509.9\n   dist_park               18654.5\n   dist_good_primary        3981.3\n   dist_supermarket         3585.9\n   n_kindergartens_350m   266019.1\n   dist_mall                2403.9\n   n_childcare_350m       358307.5\n   n_bus_350m              11921.6\n   n_primary_1km         3178565.4\n   floor_area_sqm          56712.2\n   storey_mean              9416.6\n   remaining_lease_mths     1124.6\n   ************************Diagnostic information*************************\n   Number of data points: 11680 \n   Effective number of parameters (2trace(S) - trace(S'S)): 1138.709 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 10541.29 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 276481.4 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 275423.4 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 271304.3 \n   Residual sum of squares: 1.102457e+13 \n   R-square value:  0.960804 \n   Adjusted R-square value:  0.9565695 \n\n   ***********************************************************************\n   Program stops at: 2025-11-16 15:11:41.696219 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(gwr_adaptive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Length Class                  Mode\nGW.arguments     11  -none-                 list\nGW.diagnostic     8  -none-                 list\nlm               14  lm                     list\nSDF           11680  SpatialPointsDataFrame S4  \ntimings           5  -none-                 list\nthis.call         7  -none-                 call\nFtests            0  -none-                 list\n```\n\n\n:::\n\n```{.r .cell-code}\nresale_sp$gwr_pred  <- gwr_adaptive$SDF$pred     \nresale_sp$gwr_resid <- gwr_adaptive$SDF$gwr.e   \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_test <- st_coordinates(hdb_resale_test)\nresale_sp_test <- as_Spatial(hdb_resale_test)\n\ngwr_pred_test <- gwr.predict(\n  formula = resale_price ~ \n    dist_cbd +\n    dist_eldercare +\n    dist_hawker +\n    dist_mrt +\n    dist_park +\n    dist_good_primary +\n    dist_supermarket + \n    n_kindergartens_350m +\n    dist_mall +\n    n_childcare_350m +\n    n_bus_350m +\n     n_primary_1km +\n    floor_area_sqm +\n    storey_mean +\n    remaining_lease_mths,\n  data = resale_sp_test,\n  predictdata = resale_sp_test,\n  bw = bw_adaptive,\n  kernel = \"gaussian\",\n  adaptive = TRUE,\n  longlat = FALSE\n)\n\nhdb_resale_test$pre_GWR <- gwr_pred_test$SDF$pred\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(gwr_pred_test, \"data/rds/gwr_pred_test.rds\")\nwrite_rds(hdb_resale_test, \"data/rds/hdb_resale_test_with_GWRpred.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale_test$pre_GWR <- gwr_pred_test$SDF$prediction\nnames(hdb_resale_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"month\"                \"town\"                 \"block\"               \n [4] \"street_name\"          \"flat_type\"            \"floor_area_sqm\"      \n [7] \"storey_mean\"          \"remaining_lease_mths\" \"age_of_unit\"         \n[10] \"resale_price\"         \"geometry\"             \"dist_cbd\"            \n[13] \"dist_eldercare\"       \"dist_hawker\"          \"dist_mrt\"            \n[16] \"dist_park\"            \"dist_good_primary\"    \"dist_mall\"           \n[19] \"dist_supermarket\"     \"dist_clinic\"          \"n_kindergartens_350m\"\n[22] \"n_childcare_350m\"     \"n_bus_350m\"           \"n_preschool_350m\"    \n[25] \"n_primary_1km\"        \"n_schools_1km\"        \"pre_MLR\"             \n[28] \"pre_gwRF\"             \"pre_RF\"               \"pre_GWR\"             \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(hdb_resale_test$pre_GWR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 394310  568541  632903  676305  726299 1417629 \n```\n\n\n:::\n:::\n\n\n# 8 Geographical Weighted Random Forest Model\n\n## 8.1 Data prepare for wrRF\n\nextracts spatial coordinates from the training dataset and attaches them as separate X and Y variables, enabling the geographically weighted model to account for spatial location in subsequent computations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_train <- st_coordinates(hdb_resale_train)\nhdb_train_nogeo <- hdb_resale_train %>%\n  st_drop_geometry() %>%\n  mutate(X = coords_train[, 1],\n         Y = coords_train[, 2])\n```\n:::\n\n\n# 8.2 Random Forest Model\n\nThis step trains a Random Forest regression model with 500 trees to predict HDB resale prices based on structural and locational factors, such as distance to amenities and housing attributes, while also computing variable importance to identify key predictors influencing price.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(020608)\n\nrf_model <- randomForest(\n  resale_price ~ \n    dist_cbd +\n    dist_eldercare +\n    dist_hawker +\n    dist_mrt +\n    dist_park +\n    dist_good_primary +\n    dist_supermarket + \n    n_kindergartens_350m +\n    dist_mall +\n    n_childcare_350m +\n    n_bus_350m +\n     n_primary_1km+\n    floor_area_sqm +\n    storey_mean +\n    remaining_lease_mths,\n  data  = hdb_train_nogeo,\n  ntree = 500,\n  importance = TRUE\n)\n```\n:::\n\n\n## 8.3 GWRF Bandwidth Selection\n\nAfter testing, since running the following code would take up to 16 days, we reduced the step size to 5. The final selected bandwidth was 45, but its performance in the model turned out to be unsatisfactory.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# set.seed(020608)\n# \n# bw_gwRF <- grf.bw(\n#   formula = resale_price ~ \n#     dist_cbd +\n#     dist_eldercare +\n#     dist_hawker +\n#     dist_mrt +\n#     dist_park +\n#     dist_good_primary +\n#     dist_supermarket + \n#     n_kindergartens_350m +\n#     dist_mall +\n#     n_childcare_350m +\n#     n_bus_350m +\n#      n_primary_1km+\n#     floor_area_sqm +\n#     storey_mean +\n#     remaining_lease_mths,\n#   dataset = hdb_train_nogeo,   \n#   kernel  = \"adaptive\",\n#   coords  = coords_train,      \n#   bw.min  = 30,              \n#   bw.max  = 100,\n#   step    = 1,\n#   trees   = 300,              \n#   geo.weighted = TRUE\n# )\n# \n# bw_gwRF$best.bw        \n# head(bw_gwRF$tested.bandwidths)  \n```\n:::\n\n\nUsing the optimal bandwidth obtained in the previous step, a Geographically Weighted Random Forest (gwRF) model was calibrated to capture both spatial heterogeneity and nonlinear relationships in HDB resale prices. The model incorporates 300 decision trees and applies an adaptive kernel to assign spatial weights based on proximity. This allows the gwRF to adjust prediction relationships locally across different geographic areas, providing a more spatially nuanced understanding of housing price determinants.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(020608)\n\ngwRF_adaptive <- grf(formula = resale_price ~ \n    dist_cbd +\n    dist_eldercare +\n    dist_hawker +\n    dist_mrt +\n    dist_park +\n    dist_good_primary +\n    dist_supermarket + \n    n_kindergartens_350m+\n    dist_mall +\n    n_childcare_350m +\n    n_bus_350m +\n     n_primary_1km +\n    floor_area_sqm +\n    storey_mean +\n    remaining_lease_mths,\n                     dframe=hdb_train_nogeo, \n                     bw = 45,\n                     ntree = 300,\n                     kernel=\"adaptive\",\n                     verbose = TRUE,\n                     coords=coords_train)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(gwRF_adaptive, \"data/rds/gwRF_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## 8.4 Variable Importance Analysis\n\nThis step extracts and ranks the variable importance values from the Global Model component of the Geographically Weighted Random Forest (gwRF).\n\nThe results indicate that distance to CBD (dist_cbd) and remaining lease months are the two most influential predictors of HDB resale prices, highlighting the dominant roles of location centrality and lease duration in determining housing value. Other key contributors include storey_mean, distance to good primary schools, and floor area, reflecting the significance of both structural attributes and educational accessibility.\n\nIn contrast, proximity to local amenities such as kindergartens, childcare centres, and bus stops has relatively lower importance, suggesting that macro-location and property characteristics have stronger impacts on resale price variation than minor neighborhood facilities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwrf_importance <- gwRF_adaptive$Global.Model$variable.importance\nsort(gwrf_importance, decreasing = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            dist_cbd remaining_lease_mths          storey_mean \n        9.690262e+13         7.019662e+13         2.822726e+13 \n   dist_good_primary       floor_area_sqm             dist_mrt \n        2.353144e+13         1.061061e+13         1.045175e+13 \n      dist_eldercare          dist_hawker            dist_park \n        8.238091e+12         6.827063e+12         6.080649e+12 \n           dist_mall        n_primary_1km     dist_supermarket \n        5.700043e+12         4.532240e+12         3.405118e+12 \n          n_bus_350m     n_childcare_350m n_kindergartens_350m \n        1.969431e+12         1.605800e+12         1.173038e+12 \n```\n\n\n:::\n:::\n\n\n# 9 Model evaluation\n\n## 9.1 Test Data Preparation\n\nThis step prepares the test dataset for model evaluation by extracting the spatial coordinates (X, Y) from the geometry of each HDB resale record.\n\nAfter removing the spatial geometry using st_drop_geometry(), the coordinate values are added back as numeric columns.\n\nThis transformation enables spatial models such as the Geographically Weighted Random Forest (gwRF) to access each observation’s location explicitly for geographically weighted prediction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_test <- st_coordinates(hdb_resale_test)\nhdb_test_nogeo <- hdb_resale_test %>% \n  st_drop_geometry() %>%\n  mutate(\n    X = coords_test[, 1],\n    Y = coords_test[, 2]\n  )\n```\n:::\n\n\n## 9.2 Model Prediction on Test Data\n\nThis step generates predicted resale prices for the test dataset using both models — the Multiple Linear Regression (MLR) and the Geographically Weighted Random Forest (gwRF).\n\nFor MLR, predictions are computed based on the global regression equation derived from the training data.\n\nFor gwRF, predictions are spatially adjusted using each observation’s coordinates (X, Y) with local and global weighting parameters (local.w=1, global.w=0), allowing the model to account for spatial heterogeneity and produce location-specific price estimates.\n\nFor the Random Forest (RF) model, predictions are generated using the ensemble of 500 decision trees trained on the full set of structural and locational features, enabling the model to capture complex nonlinear relationships between predictors and resale prices without considering spatial weighting.\n\n### 9.2.1 MLR\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale_test$pre_MLR <- predict(object = resale_mlr,\n                                       newdata = hdb_resale_test)\n```\n:::\n\n\n### 9.2.2 gwRF\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale_test$pre_gwRF <- predict.grf(gwRF_adaptive,\n                                            hdb_test_nogeo, \n                                            x.var.name=\"X\",\n                                            y.var.name=\"Y\", \n                                            local.w=1,\n                                            global.w=0)\n```\n:::\n\n\n### 9.2.3 RF\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale_test$pre_RF <- predict(\n  rf_model,\n  newdata = hdb_test_nogeo\n)\n```\n:::\n\n\n### 9.2.4 GWR\n\nThe prediction part of GWR has already been completed in Section 7.6 (Geospatial Weighted Regression Model) above.\n\n## 9.3 Model Performance Comparison (RMSE)\n\nThis step evaluates and compares the predictive performance of the Multiple Linear Regression (MLR), Geographically Weighted Regression (GWR), Random Forest (RF), and Geographically Weighted Random Forest (gwRF) models using the Root Mean Square Error (RMSE) metric, where lower values indicate higher prediction accuracy.\n\nThe results show that the GWR model (RMSE = 34,623.06) achieves the highest prediction accuracy, followed closely by the RF model (RMSE = 35,399.63) and the MLR model (RMSE = 77,431.47). In contrast, the gwRF model (RMSE = 155,659.39) performs significantly worse on the test dataset.\n\nThese findings suggest that accounting for spatial heterogeneity through GWR effectively improves predictive accuracy compared to the global MLR model, while the nonlinear ensemble structure of the RF also captures complex relationships between structural and locational factors well. However, the gwRF model underperforms—likely due to the suboptimal bandwidth selection—indicating that excessive localization in combination with nonlinear learning may have led to overfitting and unstable predictions. Overall, spatial effects in this dataset can be sufficiently explained by either local linear models (GWR) or global nonlinear models (RF), without the additional complexity introduced by gwRF.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMLR_RMSE  <- rmse(hdb_resale_test$resale_price, hdb_resale_test$pre_MLR)\nRF_RMSE   <- rmse(hdb_resale_test$resale_price, hdb_resale_test$pre_RF)\ngwRF_RMSE <- rmse(hdb_resale_test$resale_price, hdb_resale_test$pre_gwRF)\nGWR_RMSE  <- rmse(hdb_resale_test$resale_price, hdb_resale_test$pre_GWR)\n\nRMSE_results <- data.frame(\n  Model = c(\"Multiple Linear Regression\",\n            \"Geographically Weighted Regression\",\n            \"Random Forest\",\n            \"Geographically Weighted Random Forest\"),\n  RMSE  = c(MLR_RMSE,\n            GWR_RMSE,\n            RF_RMSE,\n            gwRF_RMSE)\n)\n\nknitr::kable(RMSE_results, caption = \"RMSE Comparison of Four Model Predictions\")\n```\n\n::: {.cell-output-display}\n\n\nTable: RMSE Comparison of Four Model Predictions\n\n|Model                                 |      RMSE|\n|:-------------------------------------|---------:|\n|Multiple Linear Regression            |  77458.27|\n|Geographically Weighted Regression    |  34623.06|\n|Random Forest                         |  35552.64|\n|Geographically Weighted Random Forest | 155659.39|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRMSE_results <- data.frame(\n  Model = c(\"MLR\",\n            \"GWR\",\n            \"RF\",\n            \"GWRF\"),\n  RMSE  = c(MLR_RMSE,\n            GWR_RMSE,\n            RF_RMSE,\n            gwRF_RMSE)\n)\n\nggplot(RMSE_results, aes(x = reorder(Model, RMSE), y = RMSE, fill = Model)) +\n  geom_bar(stat = \"identity\", width = 0.6, color = \"black\") +\n  geom_text(aes(label = round(RMSE, 0)), vjust = -0.5, size = 4) +\n  scale_fill_manual(values = c(\"#1b9e77\", \"#66c2a5\", \"#7570b3\", \"#d95f02\")) +\n  labs(\n    title = \"RMSE Comparison of Model Predictions\",\n    x = \"Model\",\n    y = \"Root Mean Square Error (S$)\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5, face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-112-1.png){width=672}\n:::\n:::\n\n\n## 9.4 Visualization of Prediction Results\n\nThe Multiple Linear Regression (MLR) model shows a moderately tight clustering of predicted values along the diagonal, indicating decent overall accuracy but a slight underestimation at higher price levels.\n\nThe Geographically Weighted Regression (GWR) model demonstrates the strongest performance, with predictions closely aligned along the 45° line and minimal dispersion, suggesting that accounting for spatial heterogeneity effectively improves predictive accuracy compared to the global MLR model.\n\nThe Random Forest (RF) model also performs well, with a dense concentration of points along the diagonal and slightly less bias across the full price range, reflecting its ability to capture complex nonlinear relationships between structural and locational factors.\n\nIn contrast, the Geographically Weighted Random Forest (gwRF) model exhibits a much wider spread of points and clear systematic underestimation, particularly for higher-priced flats. This poor performance is likely attributed to the suboptimal bandwidth selection, which caused the model to over-localize and lose generalization power. As a result, the added spatial weighting failed to enhance predictive accuracy in this dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_MLR <- ggplot(data = hdb_resale_test,\n                   aes(x = pre_MLR,\n                       y = resale_price)) +\n  geom_point(alpha = 0.6) + \n  ggtitle(\"MLR\") +\n  xlab(\"Predicted Price\") +\n  ylab(\"Actual Price\")\n\nplot_GWR <- ggplot(data = hdb_resale_test,\n                   aes(x = pre_GWR,\n                       y = resale_price)) +\n  geom_point(alpha = 0.6) + \n  ggtitle(\"GWR\") +\n  xlab(\"Predicted Price\") +\n  ylab(\"Actual Price\")\n\nplot_RF <- ggplot(data = hdb_resale_test,\n                  aes(x = pre_RF,\n                      y = resale_price)) +\n  geom_point(alpha = 0.6) + \n  ggtitle(\"RF\") +\n  xlab(\"Predicted Price\") +\n  ylab(\"Actual Price\")\n\nplot_gwRF <- ggplot(data = hdb_resale_test,\n                    aes(x = pre_gwRF,\n                        y = resale_price)) +\n  geom_point(alpha = 0.6) + \n  ggtitle(\"gwRF\") +\n  xlab(\"Predicted Price\") +\n  ylab(\"Actual Price\")\n\nggarrange(plot_MLR, plot_GWR, plot_RF, plot_gwRF,\n           ncol = 2, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-113-1.png){width=672}\n:::\n:::\n\n\n## 9.5 Spatial Error Analysis\n\nThe RF model performs well across all regions, with the Central and East regions showing the highest spatial consistency. The North and West regions exhibit mild bias — underestimation and overestimation, respectively — which may reflect regional housing market variations not fully captured by the predictors.\n\nOverall, the model tends to slightly underestimate resale prices, particularly in peripheral residential zones, while a few high-value clusters near the CBD and Queenstown areas are marginally overestimated. Despite these local discrepancies, the model demonstrates strong robustness and no systemic spatial bias, confirming that the Random Forest successfully generalizes price patterns across Singapore’s HDB market.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale_test <- hdb_resale_test %>%\n  mutate(\n    error_vs_RF = resale_price - pre_RF\n  )\ncommon_breaks <- c(-Inf, seq(-400000, 400000, by = 200000), Inf)\n\n# base map\nbase_map <- tm_shape(mpsz) +\n  tm_polygons(\"REGION_N\", alpha = 0.4, border.col = \"white\") +\n  tm_shape(hdb_resale_test)\n\nmap_error_vs_RF <- base_map +\n  tm_dots(\n    col = \"error_vs_RF\",\n    breaks = common_breaks,\n    palette = \"-RdYlBu\",   # red = overestimate, blue = underestimate\n    size = 0.2,\n    alpha = 0.9,\n    title = \"Error (S$)\",\n    contrast = c(0.3, 1)\n  ) +\n  tm_layout(\n    main.title = \"Random Forest Model Prediction Errors\",\n    main.title.size = 1,\n    legend.outside = TRUE\n  )\n\nmap_error_vs_RF\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-114-1.png){width=672}\n:::\n:::\n\n\n\n\n# 10 Conclusion\n\nThis study examined the resale prices of 4-room HDB flats in Singapore from July 2024 to September 2025 using Multiple Linear Regression (MLR), Geographically Weighted Regression (GWR), Random Forest (RF), and Geographically Weighted Random Forest (gwRF) models. Structural attributes (e.g., floor area, storey level, remaining lease) and locational factors (e.g., distance to CBD, MRT, parks, and schools) were incorporated to assess their influence on price variation.\n\nThe MLR model achieved a strong fit (adjusted R² = 0.79) and reasonable accuracy (RMSE ≈ S\\$77,431), but the Moran’s I test (0.327, p \\< 0.001) revealed spatial autocorrelation in residuals, indicating that global linear assumptions could not fully capture spatial heterogeneity.\n\nThe GWR model effectively mitigated spatial dependence and achieved the lowest RMSE (≈ S\\$34,623), showing that allowing coefficients to vary across space can better reflect local market dynamics.\n\nThe RF model also performed competitively (RMSE ≈ S\\$35,400), capturing complex nonlinear relationships between structural and locational features. Spatial error visualization confirmed that the RF model generalizes well across Singapore — performing most accurately in the Central and East regions, while slightly underestimating prices in peripheral areas and marginally overestimating in the CBD and Queenstown.\n\nThe gwRF model, in theory, should outperform all other models by combining the spatial adaptivity of GWR with the nonlinear learning capacity of RF, thus reducing both spatial bias and global fitting errors. However, in this study, the gwRF model yielded higher RMSE (≈ S\\$155,659) and right-skewed residuals, primarily due to suboptimal bandwidth selection and potential parameter interaction effects. These limitations likely caused over-localization and instability in predictions. Future research should refine the bandwidth optimization process, explore alternative kernel strategies, and consider larger or more diverse datasets to fully realize the theoretical potential of gwRF.\n\nOverall, the results suggest that spatial heterogeneity in Singapore’s HDB resale market can be effectively explained by either local linear models (GWR) or global nonlinear models (RF). The RF model currently provides the best balance between predictive accuracy, robustness, and interpretability, while the gwRF framework remains a promising but computationally sensitive method deserving of further exploration.\n\n# 11 References\n\nKam Tin Seong. *R for Geospatial Data Science and Analytics*. Retrieved October 30, 2025, from <https://r4gdsa.netlify.app/chap14.html>\n\nChristover Manafe. *Take-home Exercise 03 — ISSS626: Geospatial Analytics and Applications*. from <https://isss626-camanafe.netlify.app/take_home_ex/take_home_ex03/take_home_ex03#conclusion>\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}