---
title: "test"
format: html
---

```{r}
pacman::p_load(tidyverse,sf,lwgeom,terra,tmap,httr,
               rvest,lubridate,spatstat.geom,spatstat.explore,stpp)
```

```{r}

folder_path <- "data/aspatial"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$",
                        full.names = TRUE)

acra_data <- file_list %>%
  map_dfr(read_csv)
```


```{r}
acra_data
```


```{r}
library(dplyr)
library(ggplot2)
library(lubridate)


acra_data <- acra_data %>%
  mutate(registration_incorporation_date = as.Date(registration_incorporation_date))


monthly_counts <- acra_data %>%
  filter(registration_incorporation_date >= as.Date("1974-01-01"),
         registration_incorporation_date <= as.Date("2025-12-31")) %>%
  mutate(year_month = floor_date(registration_incorporation_date, "month")) %>%
  group_by(year_month) %>%
  summarise(company_count = n(), .groups = "drop")


ggplot(monthly_counts, aes(x = year_month, y = company_count)) +
  geom_line(color = "steelblue") +
  labs(title = "Monthly Company Registrations in Singapore (1974–2025)",
       x = "Year",
       y = "Number of Registrations") +
  theme_minimal()
```



```{r}
library(ggplot2)
library(plotly)

p <- ggplot(monthly_counts, aes(x = year_month, y = company_count)) +
  geom_line(color = "steelblue") +
  labs(title = "Monthly Company Registrations in Singapore (1974–2025)",
       x = "Year",
       y = "Number of Registrations") +
  theme_minimal()

ggplotly(p)
```
```{r}
library(dplyr)
library(ggplot2)

library(dplyr)
library(ggplot2)
library(lubridate)

library(dplyr)
library(ggplot2)
library(lubridate)

status_by_month <- acra_data %>%
  filter(entity_status_description %in% c("Live", "Cancelled", "Terminated"),
         registration_incorporation_date >= as.Date("1975-01-01"),
         registration_incorporation_date <= as.Date("2025-12-31")) %>%
  mutate(year_month = floor_date(registration_incorporation_date, "month")) %>%
  group_by(year_month, entity_status_description) %>%
  summarise(count = n(), .groups = "drop")

# 按月折线图
ggplot(status_by_month, aes(x = year_month, y = count, color = entity_status_description)) +
  geom_line(size = 0.8) +
  labs(title = "Trends of Entity Status by Month (1975–2025)",
       x = "Year-Month",
       y = "Number of Entities",
       color = "Entity Status") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}

```